// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data-acquisition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Data.Acquisition {

  /// <summary>Holder for reflection information generated from data-acquisition.proto</summary>
  public static partial class DataAcquisitionReflection {

    #region Descriptor
    /// <summary>File descriptor for data-acquisition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataAcquisitionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZkYXRhLWFjcXVpc2l0aW9uLnByb3RvEhBkYXRhLmFjcXVpc2l0aW9uGhtn",
            "b29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90",
            "aW1lc3RhbXAucHJvdG8aC3JvYm90LnByb3RvGhJ0ZWxlb3BlcmF0b3IucHJv",
            "dG8i7wQKDVNlc3Npb25QYXJhbXMSLAoFcm9ib3QYASABKAsyHS5kYXRhLmFj",
            "cXVpc2l0aW9uLnJvYm90LlJvYm90EkEKDHRlbGVvcGVyYXRvchgCIAEoCzIr",
            "LmRhdGEuYWNxdWlzaXRpb24udGVsZW9wZXJhdG9yLlRlbGVvcGVyYXRvchIP",
            "CgdyZXBvX2lkGAMgASgJEhgKEHRhc2tfZGVzY3JpcHRpb24YBCABKAkSGAoQ",
            "bmJfZXBpc29kZXNfZ29hbBgFIAEoBRIWCg5lcGlzb2RlX3RpbWVfcxgGIAEo",
            "BRIUCgxyZXNldF90aW1lX3MYByABKAUSEAoDZnBzGAggASgFSACIAQESFwoK",
            "dXNlX3ZpZGVvcxgJIAEoCEgBiAEBEhEKBHJvb3QYDyABKAlIAogBARIOCgZy",
            "ZXN1bWUYECABKAgSEwoLcHVzaF90b19odWIYFCABKAgSDwoHcHJpdmF0ZRgV",
            "IAEoCBInChpudW1faW1hZ2Vfd3JpdGVyX3Byb2Nlc3NlcxgZIAEoBUgDiAEB",
            "EjAKI251bV9pbWFnZV93cml0ZXJfdGhyZWFkc19wZXJfY2FtZXJhGBogASgF",
            "SASIAQESJgoZdmlkZW9fZW5jb2RpbmdfYmF0Y2hfc2l6ZRgbIAEoBUgFiAEB",
            "QgYKBF9mcHNCDQoLX3VzZV92aWRlb3NCBwoFX3Jvb3RCHQobX251bV9pbWFn",
            "ZV93cml0ZXJfcHJvY2Vzc2VzQiYKJF9udW1faW1hZ2Vfd3JpdGVyX3RocmVh",
            "ZHNfcGVyX2NhbWVyYUIcChpfdmlkZW9fZW5jb2RpbmdfYmF0Y2hfc2l6ZSIp",
            "CgtEYXRhc2V0Um9vdBIRCgRyb290GAEgASgJSACIAQFCBwoFX3Jvb3QilQEK",
            "B0RhdGFzZXQSFAoMZGF0YXNldF9uYW1lGAEgASgJEjIKBnB1c2hlZBgCIAEo",
            "DjIiLmRhdGEuYWNxdWlzaXRpb24uRGF0YXNldFB1c2hTdGF0ZRITCgtuYl9l",
            "cGlzb2RlcxgDIAEoBRIrCgRyb290GAogASgLMh0uZGF0YS5hY3F1aXNpdGlv",
            "bi5EYXRhc2V0Um9vdCI6CgtEYXRhc2V0TGlzdBIrCghkYXRhc2V0cxgBIAMo",
            "CzIZLmRhdGEuYWNxdWlzaXRpb24uRGF0YXNldCIgCglBY3Rpb25BY2sSEwoL",
            "c3VjY2Vzc19hY2sYASABKAgiIAoNRXBpc29kZVJhdGluZxIPCgdzdWNjZXNz",
            "GAEgASgIKlEKEERhdGFzZXRQdXNoU3RhdGUSCwoHVU5LTk9XThAAEg4KCkxP",
            "Q0FMX09OTFkQARIUChBQQVJUSUFMTFlfUFVTSEVEEAISCgoGUFVTSEVEEAMy",
            "6gcKFkRhdGFBY3F1aXNpdGlvblNlcnZpY2USTgoOR2V0RGF0YXNldExpc3QS",
            "HS5kYXRhLmFjcXVpc2l0aW9uLkRhdGFzZXRSb290Gh0uZGF0YS5hY3F1aXNp",
            "dGlvbi5EYXRhc2V0TGlzdBJKChBBZGREYXRhc2V0VG9MaXN0EhkuZGF0YS5h",
            "Y3F1aXNpdGlvbi5EYXRhc2V0GhsuZGF0YS5hY3F1aXNpdGlvbi5BY3Rpb25B",
            "Y2sSTwoVUmVtb3ZlRGF0YXNldEZyb21MaXN0EhkuZGF0YS5hY3F1aXNpdGlv",
            "bi5EYXRhc2V0GhsuZGF0YS5hY3F1aXNpdGlvbi5BY3Rpb25BY2sSTQoTVXBk",
            "YXRlRGF0YXNldEluTGlzdBIZLmRhdGEuYWNxdWlzaXRpb24uRGF0YXNldBob",
            "LmRhdGEuYWNxdWlzaXRpb24uQWN0aW9uQWNrEk4KEENsZWFyRGF0YXNldExp",
            "c3QSHS5kYXRhLmFjcXVpc2l0aW9uLkRhdGFzZXRSb290GhsuZGF0YS5hY3F1",
            "aXNpdGlvbi5BY3Rpb25BY2sSTAoMU3RhcnRTZXNzaW9uEh8uZGF0YS5hY3F1",
            "aXNpdGlvbi5TZXNzaW9uUGFyYW1zGhsuZGF0YS5hY3F1aXNpdGlvbi5BY3Rp",
            "b25BY2sSQgoLU3RvcFNlc3Npb24SFi5nb29nbGUucHJvdG9idWYuRW1wdHka",
            "Gy5kYXRhLmFjcXVpc2l0aW9uLkFjdGlvbkFjaxJDCgxTdGFydEVwaXNvZGUS",
            "Fi5nb29nbGUucHJvdG9idWYuRW1wdHkaGy5kYXRhLmFjcXVpc2l0aW9uLkFj",
            "dGlvbkFjaxJCCgtTdG9wRXBpc29kZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0",
            "eRobLmRhdGEuYWNxdWlzaXRpb24uQWN0aW9uQWNrEksKC1NhdmVFcGlzb2Rl",
            "Eh8uZGF0YS5hY3F1aXNpdGlvbi5FcGlzb2RlUmF0aW5nGhsuZGF0YS5hY3F1",
            "aXNpdGlvbi5BY3Rpb25BY2sSRAoNVXBsb2FkU2Vzc2lvbhIWLmdvb2dsZS5w",
            "cm90b2J1Zi5FbXB0eRobLmRhdGEuYWNxdWlzaXRpb24uQWN0aW9uQWNrEk0K",
            "DVJlbW92ZVNlc3Npb24SHy5kYXRhLmFjcXVpc2l0aW9uLlNlc3Npb25QYXJh",
            "bXMaGy5kYXRhLmFjcXVpc2l0aW9uLkFjdGlvbkFjaxJHChBDbGVhckFsbFNl",
            "c3Npb25zEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhsuZGF0YS5hY3F1aXNp",
            "dGlvbi5BY3Rpb25BY2tiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Data.Acquisition.Robot.RobotReflection.Descriptor, global::Data.Acquisition.Teleoperator.TeleoperatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Data.Acquisition.DatasetPushState), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.SessionParams), global::Data.Acquisition.SessionParams.Parser, new[]{ "Robot", "Teleoperator", "RepoId", "TaskDescription", "NbEpisodesGoal", "EpisodeTimeS", "ResetTimeS", "Fps", "UseVideos", "Root", "Resume", "PushToHub", "Private", "NumImageWriterProcesses", "NumImageWriterThreadsPerCamera", "VideoEncodingBatchSize" }, new[]{ "Fps", "UseVideos", "Root", "NumImageWriterProcesses", "NumImageWriterThreadsPerCamera", "VideoEncodingBatchSize" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.DatasetRoot), global::Data.Acquisition.DatasetRoot.Parser, new[]{ "Root" }, new[]{ "Root" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.Dataset), global::Data.Acquisition.Dataset.Parser, new[]{ "DatasetName", "Pushed", "NbEpisodes", "Root" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.DatasetList), global::Data.Acquisition.DatasetList.Parser, new[]{ "Datasets" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.ActionAck), global::Data.Acquisition.ActionAck.Parser, new[]{ "SuccessAck" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.EpisodeRating), global::Data.Acquisition.EpisodeRating.Parser, new[]{ "Success" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DatasetPushState {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("LOCAL_ONLY")] LocalOnly = 1,
    [pbr::OriginalName("PARTIALLY_PUSHED")] PartiallyPushed = 2,
    [pbr::OriginalName("PUSHED")] Pushed = 3,
  }

  #endregion

  #region Messages
  public sealed partial class SessionParams : pb::IMessage<SessionParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SessionParams> _parser = new pb::MessageParser<SessionParams>(() => new SessionParams());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SessionParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionParams(SessionParams other) : this() {
      _hasBits0 = other._hasBits0;
      robot_ = other.robot_ != null ? other.robot_.Clone() : null;
      teleoperator_ = other.teleoperator_ != null ? other.teleoperator_.Clone() : null;
      repoId_ = other.repoId_;
      taskDescription_ = other.taskDescription_;
      nbEpisodesGoal_ = other.nbEpisodesGoal_;
      episodeTimeS_ = other.episodeTimeS_;
      resetTimeS_ = other.resetTimeS_;
      fps_ = other.fps_;
      useVideos_ = other.useVideos_;
      root_ = other.root_;
      resume_ = other.resume_;
      pushToHub_ = other.pushToHub_;
      private_ = other.private_;
      numImageWriterProcesses_ = other.numImageWriterProcesses_;
      numImageWriterThreadsPerCamera_ = other.numImageWriterThreadsPerCamera_;
      videoEncodingBatchSize_ = other.videoEncodingBatchSize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionParams Clone() {
      return new SessionParams(this);
    }

    /// <summary>Field number for the "robot" field.</summary>
    public const int RobotFieldNumber = 1;
    private global::Data.Acquisition.Robot.Robot robot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Data.Acquisition.Robot.Robot Robot {
      get { return robot_; }
      set {
        robot_ = value;
      }
    }

    /// <summary>Field number for the "teleoperator" field.</summary>
    public const int TeleoperatorFieldNumber = 2;
    private global::Data.Acquisition.Teleoperator.Teleoperator teleoperator_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Data.Acquisition.Teleoperator.Teleoperator Teleoperator {
      get { return teleoperator_; }
      set {
        teleoperator_ = value;
      }
    }

    /// <summary>Field number for the "repo_id" field.</summary>
    public const int RepoIdFieldNumber = 3;
    private string repoId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RepoId {
      get { return repoId_; }
      set {
        repoId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "task_description" field.</summary>
    public const int TaskDescriptionFieldNumber = 4;
    private string taskDescription_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskDescription {
      get { return taskDescription_; }
      set {
        taskDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nb_episodes_goal" field.</summary>
    public const int NbEpisodesGoalFieldNumber = 5;
    private int nbEpisodesGoal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NbEpisodesGoal {
      get { return nbEpisodesGoal_; }
      set {
        nbEpisodesGoal_ = value;
      }
    }

    /// <summary>Field number for the "episode_time_s" field.</summary>
    public const int EpisodeTimeSFieldNumber = 6;
    private int episodeTimeS_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EpisodeTimeS {
      get { return episodeTimeS_; }
      set {
        episodeTimeS_ = value;
      }
    }

    /// <summary>Field number for the "reset_time_s" field.</summary>
    public const int ResetTimeSFieldNumber = 7;
    private int resetTimeS_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResetTimeS {
      get { return resetTimeS_; }
      set {
        resetTimeS_ = value;
      }
    }

    /// <summary>Field number for the "fps" field.</summary>
    public const int FpsFieldNumber = 8;
    private readonly static int FpsDefaultValue = 0;

    private int fps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Fps {
      get { if ((_hasBits0 & 1) != 0) { return fps_; } else { return FpsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        fps_ = value;
      }
    }
    /// <summary>Gets whether the "fps" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFps {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "fps" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFps() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "use_videos" field.</summary>
    public const int UseVideosFieldNumber = 9;
    private readonly static bool UseVideosDefaultValue = false;

    private bool useVideos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UseVideos {
      get { if ((_hasBits0 & 2) != 0) { return useVideos_; } else { return UseVideosDefaultValue; } }
      set {
        _hasBits0 |= 2;
        useVideos_ = value;
      }
    }
    /// <summary>Gets whether the "use_videos" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUseVideos {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "use_videos" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUseVideos() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "root" field.</summary>
    public const int RootFieldNumber = 15;
    private readonly static string RootDefaultValue = "";

    private string root_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Root {
      get { return root_ ?? RootDefaultValue; }
      set {
        root_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "root" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRoot {
      get { return root_ != null; }
    }
    /// <summary>Clears the value of the "root" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRoot() {
      root_ = null;
    }

    /// <summary>Field number for the "resume" field.</summary>
    public const int ResumeFieldNumber = 16;
    private bool resume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Resume {
      get { return resume_; }
      set {
        resume_ = value;
      }
    }

    /// <summary>Field number for the "push_to_hub" field.</summary>
    public const int PushToHubFieldNumber = 20;
    private bool pushToHub_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PushToHub {
      get { return pushToHub_; }
      set {
        pushToHub_ = value;
      }
    }

    /// <summary>Field number for the "private" field.</summary>
    public const int PrivateFieldNumber = 21;
    private bool private_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Private {
      get { return private_; }
      set {
        private_ = value;
      }
    }

    /// <summary>Field number for the "num_image_writer_processes" field.</summary>
    public const int NumImageWriterProcessesFieldNumber = 25;
    private readonly static int NumImageWriterProcessesDefaultValue = 0;

    private int numImageWriterProcesses_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumImageWriterProcesses {
      get { if ((_hasBits0 & 4) != 0) { return numImageWriterProcesses_; } else { return NumImageWriterProcessesDefaultValue; } }
      set {
        _hasBits0 |= 4;
        numImageWriterProcesses_ = value;
      }
    }
    /// <summary>Gets whether the "num_image_writer_processes" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumImageWriterProcesses {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "num_image_writer_processes" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumImageWriterProcesses() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "num_image_writer_threads_per_camera" field.</summary>
    public const int NumImageWriterThreadsPerCameraFieldNumber = 26;
    private readonly static int NumImageWriterThreadsPerCameraDefaultValue = 0;

    private int numImageWriterThreadsPerCamera_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumImageWriterThreadsPerCamera {
      get { if ((_hasBits0 & 8) != 0) { return numImageWriterThreadsPerCamera_; } else { return NumImageWriterThreadsPerCameraDefaultValue; } }
      set {
        _hasBits0 |= 8;
        numImageWriterThreadsPerCamera_ = value;
      }
    }
    /// <summary>Gets whether the "num_image_writer_threads_per_camera" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumImageWriterThreadsPerCamera {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "num_image_writer_threads_per_camera" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumImageWriterThreadsPerCamera() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "video_encoding_batch_size" field.</summary>
    public const int VideoEncodingBatchSizeFieldNumber = 27;
    private readonly static int VideoEncodingBatchSizeDefaultValue = 0;

    private int videoEncodingBatchSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int VideoEncodingBatchSize {
      get { if ((_hasBits0 & 16) != 0) { return videoEncodingBatchSize_; } else { return VideoEncodingBatchSizeDefaultValue; } }
      set {
        _hasBits0 |= 16;
        videoEncodingBatchSize_ = value;
      }
    }
    /// <summary>Gets whether the "video_encoding_batch_size" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVideoEncodingBatchSize {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "video_encoding_batch_size" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVideoEncodingBatchSize() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SessionParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SessionParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Robot, other.Robot)) return false;
      if (!object.Equals(Teleoperator, other.Teleoperator)) return false;
      if (RepoId != other.RepoId) return false;
      if (TaskDescription != other.TaskDescription) return false;
      if (NbEpisodesGoal != other.NbEpisodesGoal) return false;
      if (EpisodeTimeS != other.EpisodeTimeS) return false;
      if (ResetTimeS != other.ResetTimeS) return false;
      if (Fps != other.Fps) return false;
      if (UseVideos != other.UseVideos) return false;
      if (Root != other.Root) return false;
      if (Resume != other.Resume) return false;
      if (PushToHub != other.PushToHub) return false;
      if (Private != other.Private) return false;
      if (NumImageWriterProcesses != other.NumImageWriterProcesses) return false;
      if (NumImageWriterThreadsPerCamera != other.NumImageWriterThreadsPerCamera) return false;
      if (VideoEncodingBatchSize != other.VideoEncodingBatchSize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (robot_ != null) hash ^= Robot.GetHashCode();
      if (teleoperator_ != null) hash ^= Teleoperator.GetHashCode();
      if (RepoId.Length != 0) hash ^= RepoId.GetHashCode();
      if (TaskDescription.Length != 0) hash ^= TaskDescription.GetHashCode();
      if (NbEpisodesGoal != 0) hash ^= NbEpisodesGoal.GetHashCode();
      if (EpisodeTimeS != 0) hash ^= EpisodeTimeS.GetHashCode();
      if (ResetTimeS != 0) hash ^= ResetTimeS.GetHashCode();
      if (HasFps) hash ^= Fps.GetHashCode();
      if (HasUseVideos) hash ^= UseVideos.GetHashCode();
      if (HasRoot) hash ^= Root.GetHashCode();
      if (Resume != false) hash ^= Resume.GetHashCode();
      if (PushToHub != false) hash ^= PushToHub.GetHashCode();
      if (Private != false) hash ^= Private.GetHashCode();
      if (HasNumImageWriterProcesses) hash ^= NumImageWriterProcesses.GetHashCode();
      if (HasNumImageWriterThreadsPerCamera) hash ^= NumImageWriterThreadsPerCamera.GetHashCode();
      if (HasVideoEncodingBatchSize) hash ^= VideoEncodingBatchSize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (robot_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Robot);
      }
      if (teleoperator_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Teleoperator);
      }
      if (RepoId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RepoId);
      }
      if (TaskDescription.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TaskDescription);
      }
      if (NbEpisodesGoal != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NbEpisodesGoal);
      }
      if (EpisodeTimeS != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(EpisodeTimeS);
      }
      if (ResetTimeS != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ResetTimeS);
      }
      if (HasFps) {
        output.WriteRawTag(64);
        output.WriteInt32(Fps);
      }
      if (HasUseVideos) {
        output.WriteRawTag(72);
        output.WriteBool(UseVideos);
      }
      if (HasRoot) {
        output.WriteRawTag(122);
        output.WriteString(Root);
      }
      if (Resume != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(Resume);
      }
      if (PushToHub != false) {
        output.WriteRawTag(160, 1);
        output.WriteBool(PushToHub);
      }
      if (Private != false) {
        output.WriteRawTag(168, 1);
        output.WriteBool(Private);
      }
      if (HasNumImageWriterProcesses) {
        output.WriteRawTag(200, 1);
        output.WriteInt32(NumImageWriterProcesses);
      }
      if (HasNumImageWriterThreadsPerCamera) {
        output.WriteRawTag(208, 1);
        output.WriteInt32(NumImageWriterThreadsPerCamera);
      }
      if (HasVideoEncodingBatchSize) {
        output.WriteRawTag(216, 1);
        output.WriteInt32(VideoEncodingBatchSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (robot_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Robot);
      }
      if (teleoperator_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Teleoperator);
      }
      if (RepoId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RepoId);
      }
      if (TaskDescription.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TaskDescription);
      }
      if (NbEpisodesGoal != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NbEpisodesGoal);
      }
      if (EpisodeTimeS != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(EpisodeTimeS);
      }
      if (ResetTimeS != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ResetTimeS);
      }
      if (HasFps) {
        output.WriteRawTag(64);
        output.WriteInt32(Fps);
      }
      if (HasUseVideos) {
        output.WriteRawTag(72);
        output.WriteBool(UseVideos);
      }
      if (HasRoot) {
        output.WriteRawTag(122);
        output.WriteString(Root);
      }
      if (Resume != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(Resume);
      }
      if (PushToHub != false) {
        output.WriteRawTag(160, 1);
        output.WriteBool(PushToHub);
      }
      if (Private != false) {
        output.WriteRawTag(168, 1);
        output.WriteBool(Private);
      }
      if (HasNumImageWriterProcesses) {
        output.WriteRawTag(200, 1);
        output.WriteInt32(NumImageWriterProcesses);
      }
      if (HasNumImageWriterThreadsPerCamera) {
        output.WriteRawTag(208, 1);
        output.WriteInt32(NumImageWriterThreadsPerCamera);
      }
      if (HasVideoEncodingBatchSize) {
        output.WriteRawTag(216, 1);
        output.WriteInt32(VideoEncodingBatchSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (robot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Robot);
      }
      if (teleoperator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Teleoperator);
      }
      if (RepoId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoId);
      }
      if (TaskDescription.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskDescription);
      }
      if (NbEpisodesGoal != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NbEpisodesGoal);
      }
      if (EpisodeTimeS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EpisodeTimeS);
      }
      if (ResetTimeS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResetTimeS);
      }
      if (HasFps) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Fps);
      }
      if (HasUseVideos) {
        size += 1 + 1;
      }
      if (HasRoot) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Root);
      }
      if (Resume != false) {
        size += 2 + 1;
      }
      if (PushToHub != false) {
        size += 2 + 1;
      }
      if (Private != false) {
        size += 2 + 1;
      }
      if (HasNumImageWriterProcesses) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(NumImageWriterProcesses);
      }
      if (HasNumImageWriterThreadsPerCamera) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(NumImageWriterThreadsPerCamera);
      }
      if (HasVideoEncodingBatchSize) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(VideoEncodingBatchSize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SessionParams other) {
      if (other == null) {
        return;
      }
      if (other.robot_ != null) {
        if (robot_ == null) {
          Robot = new global::Data.Acquisition.Robot.Robot();
        }
        Robot.MergeFrom(other.Robot);
      }
      if (other.teleoperator_ != null) {
        if (teleoperator_ == null) {
          Teleoperator = new global::Data.Acquisition.Teleoperator.Teleoperator();
        }
        Teleoperator.MergeFrom(other.Teleoperator);
      }
      if (other.RepoId.Length != 0) {
        RepoId = other.RepoId;
      }
      if (other.TaskDescription.Length != 0) {
        TaskDescription = other.TaskDescription;
      }
      if (other.NbEpisodesGoal != 0) {
        NbEpisodesGoal = other.NbEpisodesGoal;
      }
      if (other.EpisodeTimeS != 0) {
        EpisodeTimeS = other.EpisodeTimeS;
      }
      if (other.ResetTimeS != 0) {
        ResetTimeS = other.ResetTimeS;
      }
      if (other.HasFps) {
        Fps = other.Fps;
      }
      if (other.HasUseVideos) {
        UseVideos = other.UseVideos;
      }
      if (other.HasRoot) {
        Root = other.Root;
      }
      if (other.Resume != false) {
        Resume = other.Resume;
      }
      if (other.PushToHub != false) {
        PushToHub = other.PushToHub;
      }
      if (other.Private != false) {
        Private = other.Private;
      }
      if (other.HasNumImageWriterProcesses) {
        NumImageWriterProcesses = other.NumImageWriterProcesses;
      }
      if (other.HasNumImageWriterThreadsPerCamera) {
        NumImageWriterThreadsPerCamera = other.NumImageWriterThreadsPerCamera;
      }
      if (other.HasVideoEncodingBatchSize) {
        VideoEncodingBatchSize = other.VideoEncodingBatchSize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (robot_ == null) {
              Robot = new global::Data.Acquisition.Robot.Robot();
            }
            input.ReadMessage(Robot);
            break;
          }
          case 18: {
            if (teleoperator_ == null) {
              Teleoperator = new global::Data.Acquisition.Teleoperator.Teleoperator();
            }
            input.ReadMessage(Teleoperator);
            break;
          }
          case 26: {
            RepoId = input.ReadString();
            break;
          }
          case 34: {
            TaskDescription = input.ReadString();
            break;
          }
          case 40: {
            NbEpisodesGoal = input.ReadInt32();
            break;
          }
          case 48: {
            EpisodeTimeS = input.ReadInt32();
            break;
          }
          case 56: {
            ResetTimeS = input.ReadInt32();
            break;
          }
          case 64: {
            Fps = input.ReadInt32();
            break;
          }
          case 72: {
            UseVideos = input.ReadBool();
            break;
          }
          case 122: {
            Root = input.ReadString();
            break;
          }
          case 128: {
            Resume = input.ReadBool();
            break;
          }
          case 160: {
            PushToHub = input.ReadBool();
            break;
          }
          case 168: {
            Private = input.ReadBool();
            break;
          }
          case 200: {
            NumImageWriterProcesses = input.ReadInt32();
            break;
          }
          case 208: {
            NumImageWriterThreadsPerCamera = input.ReadInt32();
            break;
          }
          case 216: {
            VideoEncodingBatchSize = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (robot_ == null) {
              Robot = new global::Data.Acquisition.Robot.Robot();
            }
            input.ReadMessage(Robot);
            break;
          }
          case 18: {
            if (teleoperator_ == null) {
              Teleoperator = new global::Data.Acquisition.Teleoperator.Teleoperator();
            }
            input.ReadMessage(Teleoperator);
            break;
          }
          case 26: {
            RepoId = input.ReadString();
            break;
          }
          case 34: {
            TaskDescription = input.ReadString();
            break;
          }
          case 40: {
            NbEpisodesGoal = input.ReadInt32();
            break;
          }
          case 48: {
            EpisodeTimeS = input.ReadInt32();
            break;
          }
          case 56: {
            ResetTimeS = input.ReadInt32();
            break;
          }
          case 64: {
            Fps = input.ReadInt32();
            break;
          }
          case 72: {
            UseVideos = input.ReadBool();
            break;
          }
          case 122: {
            Root = input.ReadString();
            break;
          }
          case 128: {
            Resume = input.ReadBool();
            break;
          }
          case 160: {
            PushToHub = input.ReadBool();
            break;
          }
          case 168: {
            Private = input.ReadBool();
            break;
          }
          case 200: {
            NumImageWriterProcesses = input.ReadInt32();
            break;
          }
          case 208: {
            NumImageWriterThreadsPerCamera = input.ReadInt32();
            break;
          }
          case 216: {
            VideoEncodingBatchSize = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DatasetRoot : pb::IMessage<DatasetRoot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DatasetRoot> _parser = new pb::MessageParser<DatasetRoot>(() => new DatasetRoot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DatasetRoot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetRoot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetRoot(DatasetRoot other) : this() {
      root_ = other.root_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetRoot Clone() {
      return new DatasetRoot(this);
    }

    /// <summary>Field number for the "root" field.</summary>
    public const int RootFieldNumber = 1;
    private readonly static string RootDefaultValue = "";

    private string root_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Root {
      get { return root_ ?? RootDefaultValue; }
      set {
        root_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "root" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRoot {
      get { return root_ != null; }
    }
    /// <summary>Clears the value of the "root" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRoot() {
      root_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DatasetRoot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DatasetRoot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Root != other.Root) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRoot) hash ^= Root.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRoot) {
        output.WriteRawTag(10);
        output.WriteString(Root);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRoot) {
        output.WriteRawTag(10);
        output.WriteString(Root);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRoot) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Root);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DatasetRoot other) {
      if (other == null) {
        return;
      }
      if (other.HasRoot) {
        Root = other.Root;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Root = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Root = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Dataset : pb::IMessage<Dataset>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Dataset> _parser = new pb::MessageParser<Dataset>(() => new Dataset());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Dataset> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dataset() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dataset(Dataset other) : this() {
      datasetName_ = other.datasetName_;
      pushed_ = other.pushed_;
      nbEpisodes_ = other.nbEpisodes_;
      root_ = other.root_ != null ? other.root_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dataset Clone() {
      return new Dataset(this);
    }

    /// <summary>Field number for the "dataset_name" field.</summary>
    public const int DatasetNameFieldNumber = 1;
    private string datasetName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DatasetName {
      get { return datasetName_; }
      set {
        datasetName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pushed" field.</summary>
    public const int PushedFieldNumber = 2;
    private global::Data.Acquisition.DatasetPushState pushed_ = global::Data.Acquisition.DatasetPushState.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Data.Acquisition.DatasetPushState Pushed {
      get { return pushed_; }
      set {
        pushed_ = value;
      }
    }

    /// <summary>Field number for the "nb_episodes" field.</summary>
    public const int NbEpisodesFieldNumber = 3;
    private int nbEpisodes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NbEpisodes {
      get { return nbEpisodes_; }
      set {
        nbEpisodes_ = value;
      }
    }

    /// <summary>Field number for the "root" field.</summary>
    public const int RootFieldNumber = 10;
    private global::Data.Acquisition.DatasetRoot root_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Data.Acquisition.DatasetRoot Root {
      get { return root_; }
      set {
        root_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Dataset);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Dataset other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DatasetName != other.DatasetName) return false;
      if (Pushed != other.Pushed) return false;
      if (NbEpisodes != other.NbEpisodes) return false;
      if (!object.Equals(Root, other.Root)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DatasetName.Length != 0) hash ^= DatasetName.GetHashCode();
      if (Pushed != global::Data.Acquisition.DatasetPushState.Unknown) hash ^= Pushed.GetHashCode();
      if (NbEpisodes != 0) hash ^= NbEpisodes.GetHashCode();
      if (root_ != null) hash ^= Root.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DatasetName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DatasetName);
      }
      if (Pushed != global::Data.Acquisition.DatasetPushState.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Pushed);
      }
      if (NbEpisodes != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NbEpisodes);
      }
      if (root_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Root);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DatasetName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DatasetName);
      }
      if (Pushed != global::Data.Acquisition.DatasetPushState.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Pushed);
      }
      if (NbEpisodes != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NbEpisodes);
      }
      if (root_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Root);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DatasetName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DatasetName);
      }
      if (Pushed != global::Data.Acquisition.DatasetPushState.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Pushed);
      }
      if (NbEpisodes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NbEpisodes);
      }
      if (root_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Root);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Dataset other) {
      if (other == null) {
        return;
      }
      if (other.DatasetName.Length != 0) {
        DatasetName = other.DatasetName;
      }
      if (other.Pushed != global::Data.Acquisition.DatasetPushState.Unknown) {
        Pushed = other.Pushed;
      }
      if (other.NbEpisodes != 0) {
        NbEpisodes = other.NbEpisodes;
      }
      if (other.root_ != null) {
        if (root_ == null) {
          Root = new global::Data.Acquisition.DatasetRoot();
        }
        Root.MergeFrom(other.Root);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DatasetName = input.ReadString();
            break;
          }
          case 16: {
            Pushed = (global::Data.Acquisition.DatasetPushState) input.ReadEnum();
            break;
          }
          case 24: {
            NbEpisodes = input.ReadInt32();
            break;
          }
          case 82: {
            if (root_ == null) {
              Root = new global::Data.Acquisition.DatasetRoot();
            }
            input.ReadMessage(Root);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DatasetName = input.ReadString();
            break;
          }
          case 16: {
            Pushed = (global::Data.Acquisition.DatasetPushState) input.ReadEnum();
            break;
          }
          case 24: {
            NbEpisodes = input.ReadInt32();
            break;
          }
          case 82: {
            if (root_ == null) {
              Root = new global::Data.Acquisition.DatasetRoot();
            }
            input.ReadMessage(Root);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DatasetList : pb::IMessage<DatasetList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DatasetList> _parser = new pb::MessageParser<DatasetList>(() => new DatasetList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DatasetList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetList(DatasetList other) : this() {
      datasets_ = other.datasets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetList Clone() {
      return new DatasetList(this);
    }

    /// <summary>Field number for the "datasets" field.</summary>
    public const int DatasetsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Data.Acquisition.Dataset> _repeated_datasets_codec
        = pb::FieldCodec.ForMessage(10, global::Data.Acquisition.Dataset.Parser);
    private readonly pbc::RepeatedField<global::Data.Acquisition.Dataset> datasets_ = new pbc::RepeatedField<global::Data.Acquisition.Dataset>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Data.Acquisition.Dataset> Datasets {
      get { return datasets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DatasetList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DatasetList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!datasets_.Equals(other.datasets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= datasets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      datasets_.WriteTo(output, _repeated_datasets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      datasets_.WriteTo(ref output, _repeated_datasets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += datasets_.CalculateSize(_repeated_datasets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DatasetList other) {
      if (other == null) {
        return;
      }
      datasets_.Add(other.datasets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            datasets_.AddEntriesFrom(input, _repeated_datasets_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            datasets_.AddEntriesFrom(ref input, _repeated_datasets_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActionAck : pb::IMessage<ActionAck>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionAck> _parser = new pb::MessageParser<ActionAck>(() => new ActionAck());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionAck> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionAck() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionAck(ActionAck other) : this() {
      successAck_ = other.successAck_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionAck Clone() {
      return new ActionAck(this);
    }

    /// <summary>Field number for the "success_ack" field.</summary>
    public const int SuccessAckFieldNumber = 1;
    private bool successAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SuccessAck {
      get { return successAck_; }
      set {
        successAck_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionAck);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionAck other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SuccessAck != other.SuccessAck) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SuccessAck != false) hash ^= SuccessAck.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SuccessAck != false) {
        output.WriteRawTag(8);
        output.WriteBool(SuccessAck);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SuccessAck != false) {
        output.WriteRawTag(8);
        output.WriteBool(SuccessAck);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SuccessAck != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionAck other) {
      if (other == null) {
        return;
      }
      if (other.SuccessAck != false) {
        SuccessAck = other.SuccessAck;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SuccessAck = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SuccessAck = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EpisodeRating : pb::IMessage<EpisodeRating>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EpisodeRating> _parser = new pb::MessageParser<EpisodeRating>(() => new EpisodeRating());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EpisodeRating> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EpisodeRating() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EpisodeRating(EpisodeRating other) : this() {
      success_ = other.success_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EpisodeRating Clone() {
      return new EpisodeRating(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EpisodeRating);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EpisodeRating other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EpisodeRating other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
