// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data-acquisition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Data.Acquisition {

  /// <summary>Holder for reflection information generated from data-acquisition.proto</summary>
  public static partial class DataAcquisitionReflection {

    #region Descriptor
    /// <summary>File descriptor for data-acquisition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataAcquisitionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZkYXRhLWFjcXVpc2l0aW9uLnByb3RvEhBkYXRhLmFjcXVpc2l0aW9uGhtn",
            "b29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90",
            "aW1lc3RhbXAucHJvdG8i0AIKDVNlc3Npb25QYXJhbXMSJgoFcm9ib3QYASAB",
            "KA4yFy5kYXRhLmFjcXVpc2l0aW9uLlJvYm90EhQKDHNlc3Npb25fbmFtZRgC",
            "IAEoCRIYChBuYl9lcGlzb2Rlc19nb2FsGAMgASgFEhgKEGVwaXNvZGVfZHVy",
            "YXRpb24YBCABKAUSGwoTYnJlYWtfdGltZV9kdXJhdGlvbhgFIAEoBRIcChR3",
            "YXJtdXBfdGltZV9kdXJhdGlvbhgGIAEoBRIQCgNmcHMYByABKAVIAIgBARIS",
            "Cgp1c2VfdmlkZW9zGAggASgIEhgKEHRhc2tfZGVzY3JpcHRpb24YCiABKAkS",
            "FAoMZGF0YXNldF9uYW1lGA8gASgJEg4KBnJlc3VtZRgQIAEoCBITCgtwdXNo",
            "X3RvX2h1YhgUIAEoCBIPCgdvZmZsaW5lGBUgASgIQgYKBF9mcHMibgoHU2Vz",
            "c2lvbhIUCgxzZXNzaW9uX25hbWUYASABKAkSHAoUbmJfZXBpc29kZXNfcmVj",
            "b3JkZWQYAiABKAUSLwoLbGFzdF91cGRhdGUYAyABKAsyGi5nb29nbGUucHJv",
            "dG9idWYuVGltZXN0YW1wImgKB0RhdGFzZXQSFAoMZGF0YXNldF9uYW1lGAEg",
            "ASgJEjIKBnB1c2hlZBgCIAEoDjIiLmRhdGEuYWNxdWlzaXRpb24uRGF0YXNl",
            "dFB1c2hTdGF0ZRITCgtuYl9lcGlzb2RlcxgDIAEoBSI6CgtEYXRhc2V0TGlz",
            "dBIrCghkYXRhc2V0cxgBIAMoCzIZLmRhdGEuYWNxdWlzaXRpb24uRGF0YXNl",
            "dCIgCglBY3Rpb25BY2sSEwoLc3VjY2Vzc19hY2sYASABKAgiIAoNRXBpc29k",
            "ZVJhdGluZxIPCgdzdWNjZXNzGAEgASgIInEKB0VwaXNvZGUSFwoKZXBpc29k",
            "ZV9pZBgBIAEoBUgAiAEBEhAKCGR1cmF0aW9uGAIgASgFEhcKD2VwaXNvZGVf",
            "c3VjY2VzcxgDIAEoCBITCgtkZXNjcmlwdGlvbhgEIAEoCUINCgtfZXBpc29k",
            "ZV9pZCIWCgVMb2dpbhINCgV0b2tlbhgBIAEoCSpEChBEYXRhc2V0UHVzaFN0",
            "YXRlEg4KCkxPQ0FMX09OTFkQABIUChBQQVJUSUFMTFlfUFVTSEVEEAESCgoG",
            "UFVTSEVEEAIqHgoFUm9ib3QSCAoETk9ORRAAEgsKB1JFQUNIWTIQATLIBwoW",
            "RGF0YUFjcXVpc2l0aW9uU2VydmljZRJHCg5HZXREYXRhc2V0TGlzdBIWLmdv",
            "b2dsZS5wcm90b2J1Zi5FbXB0eRodLmRhdGEuYWNxdWlzaXRpb24uRGF0YXNl",
            "dExpc3QSRAoKQWRkRGF0YXNldBIZLmRhdGEuYWNxdWlzaXRpb24uRGF0YXNl",
            "dBobLmRhdGEuYWNxdWlzaXRpb24uQWN0aW9uQWNrEkcKDVJlbW92ZURhdGFz",
            "ZXQSGS5kYXRhLmFjcXVpc2l0aW9uLkRhdGFzZXQaGy5kYXRhLmFjcXVpc2l0",
            "aW9uLkFjdGlvbkFjaxJHCg1VcGRhdGVEYXRhc2V0EhkuZGF0YS5hY3F1aXNp",
            "dGlvbi5EYXRhc2V0GhsuZGF0YS5hY3F1aXNpdGlvbi5BY3Rpb25BY2sSRwoQ",
            "Q2xlYXJBbGxEYXRhc2V0cxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRobLmRh",
            "dGEuYWNxdWlzaXRpb24uQWN0aW9uQWNrEkwKDFN0YXJ0U2Vzc2lvbhIfLmRh",
            "dGEuYWNxdWlzaXRpb24uU2Vzc2lvblBhcmFtcxobLmRhdGEuYWNxdWlzaXRp",
            "b24uQWN0aW9uQWNrEkIKC1N0b3BTZXNzaW9uEhYuZ29vZ2xlLnByb3RvYnVm",
            "LkVtcHR5GhsuZGF0YS5hY3F1aXNpdGlvbi5BY3Rpb25BY2sSQwoMU3RhcnRF",
            "cGlzb2RlEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhsuZGF0YS5hY3F1aXNp",
            "dGlvbi5BY3Rpb25BY2sSQgoLU3RvcEVwaXNvZGUSFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkaGy5kYXRhLmFjcXVpc2l0aW9uLkFjdGlvbkFjaxJLCgtTYXZl",
            "RXBpc29kZRIfLmRhdGEuYWNxdWlzaXRpb24uRXBpc29kZVJhdGluZxobLmRh",
            "dGEuYWNxdWlzaXRpb24uQWN0aW9uQWNrEkQKDVVwbG9hZFNlc3Npb24SFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHkaGy5kYXRhLmFjcXVpc2l0aW9uLkFjdGlv",
            "bkFjaxJNCg1SZW1vdmVTZXNzaW9uEh8uZGF0YS5hY3F1aXNpdGlvbi5TZXNz",
            "aW9uUGFyYW1zGhsuZGF0YS5hY3F1aXNpdGlvbi5BY3Rpb25BY2sSRwoQQ2xl",
            "YXJBbGxTZXNzaW9ucxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRobLmRhdGEu",
            "YWNxdWlzaXRpb24uQWN0aW9uQWNrYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Data.Acquisition.DatasetPushState), typeof(global::Data.Acquisition.Robot), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.SessionParams), global::Data.Acquisition.SessionParams.Parser, new[]{ "Robot", "SessionName", "NbEpisodesGoal", "EpisodeDuration", "BreakTimeDuration", "WarmupTimeDuration", "Fps", "UseVideos", "TaskDescription", "DatasetName", "Resume", "PushToHub", "Offline" }, new[]{ "Fps" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.Session), global::Data.Acquisition.Session.Parser, new[]{ "SessionName", "NbEpisodesRecorded", "LastUpdate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.Dataset), global::Data.Acquisition.Dataset.Parser, new[]{ "DatasetName", "Pushed", "NbEpisodes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.DatasetList), global::Data.Acquisition.DatasetList.Parser, new[]{ "Datasets" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.ActionAck), global::Data.Acquisition.ActionAck.Parser, new[]{ "SuccessAck" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.EpisodeRating), global::Data.Acquisition.EpisodeRating.Parser, new[]{ "Success" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.Episode), global::Data.Acquisition.Episode.Parser, new[]{ "EpisodeId", "Duration", "EpisodeSuccess", "Description" }, new[]{ "EpisodeId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.Login), global::Data.Acquisition.Login.Parser, new[]{ "Token" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DatasetPushState {
    [pbr::OriginalName("LOCAL_ONLY")] LocalOnly = 0,
    [pbr::OriginalName("PARTIALLY_PUSHED")] PartiallyPushed = 1,
    [pbr::OriginalName("PUSHED")] Pushed = 2,
  }

  public enum Robot {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("REACHY2")] Reachy2 = 1,
  }

  #endregion

  #region Messages
  public sealed partial class SessionParams : pb::IMessage<SessionParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SessionParams> _parser = new pb::MessageParser<SessionParams>(() => new SessionParams());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SessionParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionParams(SessionParams other) : this() {
      _hasBits0 = other._hasBits0;
      robot_ = other.robot_;
      sessionName_ = other.sessionName_;
      nbEpisodesGoal_ = other.nbEpisodesGoal_;
      episodeDuration_ = other.episodeDuration_;
      breakTimeDuration_ = other.breakTimeDuration_;
      warmupTimeDuration_ = other.warmupTimeDuration_;
      fps_ = other.fps_;
      useVideos_ = other.useVideos_;
      taskDescription_ = other.taskDescription_;
      datasetName_ = other.datasetName_;
      resume_ = other.resume_;
      pushToHub_ = other.pushToHub_;
      offline_ = other.offline_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionParams Clone() {
      return new SessionParams(this);
    }

    /// <summary>Field number for the "robot" field.</summary>
    public const int RobotFieldNumber = 1;
    private global::Data.Acquisition.Robot robot_ = global::Data.Acquisition.Robot.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Data.Acquisition.Robot Robot {
      get { return robot_; }
      set {
        robot_ = value;
      }
    }

    /// <summary>Field number for the "session_name" field.</summary>
    public const int SessionNameFieldNumber = 2;
    private string sessionName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionName {
      get { return sessionName_; }
      set {
        sessionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nb_episodes_goal" field.</summary>
    public const int NbEpisodesGoalFieldNumber = 3;
    private int nbEpisodesGoal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NbEpisodesGoal {
      get { return nbEpisodesGoal_; }
      set {
        nbEpisodesGoal_ = value;
      }
    }

    /// <summary>Field number for the "episode_duration" field.</summary>
    public const int EpisodeDurationFieldNumber = 4;
    private int episodeDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EpisodeDuration {
      get { return episodeDuration_; }
      set {
        episodeDuration_ = value;
      }
    }

    /// <summary>Field number for the "break_time_duration" field.</summary>
    public const int BreakTimeDurationFieldNumber = 5;
    private int breakTimeDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BreakTimeDuration {
      get { return breakTimeDuration_; }
      set {
        breakTimeDuration_ = value;
      }
    }

    /// <summary>Field number for the "warmup_time_duration" field.</summary>
    public const int WarmupTimeDurationFieldNumber = 6;
    private int warmupTimeDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WarmupTimeDuration {
      get { return warmupTimeDuration_; }
      set {
        warmupTimeDuration_ = value;
      }
    }

    /// <summary>Field number for the "fps" field.</summary>
    public const int FpsFieldNumber = 7;
    private readonly static int FpsDefaultValue = 0;

    private int fps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Fps {
      get { if ((_hasBits0 & 1) != 0) { return fps_; } else { return FpsDefaultValue; } }
      set {
        _hasBits0 |= 1;
        fps_ = value;
      }
    }
    /// <summary>Gets whether the "fps" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFps {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "fps" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFps() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "use_videos" field.</summary>
    public const int UseVideosFieldNumber = 8;
    private bool useVideos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UseVideos {
      get { return useVideos_; }
      set {
        useVideos_ = value;
      }
    }

    /// <summary>Field number for the "task_description" field.</summary>
    public const int TaskDescriptionFieldNumber = 10;
    private string taskDescription_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskDescription {
      get { return taskDescription_; }
      set {
        taskDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dataset_name" field.</summary>
    public const int DatasetNameFieldNumber = 15;
    private string datasetName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DatasetName {
      get { return datasetName_; }
      set {
        datasetName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resume" field.</summary>
    public const int ResumeFieldNumber = 16;
    private bool resume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Resume {
      get { return resume_; }
      set {
        resume_ = value;
      }
    }

    /// <summary>Field number for the "push_to_hub" field.</summary>
    public const int PushToHubFieldNumber = 20;
    private bool pushToHub_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PushToHub {
      get { return pushToHub_; }
      set {
        pushToHub_ = value;
      }
    }

    /// <summary>Field number for the "offline" field.</summary>
    public const int OfflineFieldNumber = 21;
    private bool offline_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Offline {
      get { return offline_; }
      set {
        offline_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SessionParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SessionParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Robot != other.Robot) return false;
      if (SessionName != other.SessionName) return false;
      if (NbEpisodesGoal != other.NbEpisodesGoal) return false;
      if (EpisodeDuration != other.EpisodeDuration) return false;
      if (BreakTimeDuration != other.BreakTimeDuration) return false;
      if (WarmupTimeDuration != other.WarmupTimeDuration) return false;
      if (Fps != other.Fps) return false;
      if (UseVideos != other.UseVideos) return false;
      if (TaskDescription != other.TaskDescription) return false;
      if (DatasetName != other.DatasetName) return false;
      if (Resume != other.Resume) return false;
      if (PushToHub != other.PushToHub) return false;
      if (Offline != other.Offline) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Robot != global::Data.Acquisition.Robot.None) hash ^= Robot.GetHashCode();
      if (SessionName.Length != 0) hash ^= SessionName.GetHashCode();
      if (NbEpisodesGoal != 0) hash ^= NbEpisodesGoal.GetHashCode();
      if (EpisodeDuration != 0) hash ^= EpisodeDuration.GetHashCode();
      if (BreakTimeDuration != 0) hash ^= BreakTimeDuration.GetHashCode();
      if (WarmupTimeDuration != 0) hash ^= WarmupTimeDuration.GetHashCode();
      if (HasFps) hash ^= Fps.GetHashCode();
      if (UseVideos != false) hash ^= UseVideos.GetHashCode();
      if (TaskDescription.Length != 0) hash ^= TaskDescription.GetHashCode();
      if (DatasetName.Length != 0) hash ^= DatasetName.GetHashCode();
      if (Resume != false) hash ^= Resume.GetHashCode();
      if (PushToHub != false) hash ^= PushToHub.GetHashCode();
      if (Offline != false) hash ^= Offline.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Robot != global::Data.Acquisition.Robot.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Robot);
      }
      if (SessionName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionName);
      }
      if (NbEpisodesGoal != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NbEpisodesGoal);
      }
      if (EpisodeDuration != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(EpisodeDuration);
      }
      if (BreakTimeDuration != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(BreakTimeDuration);
      }
      if (WarmupTimeDuration != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(WarmupTimeDuration);
      }
      if (HasFps) {
        output.WriteRawTag(56);
        output.WriteInt32(Fps);
      }
      if (UseVideos != false) {
        output.WriteRawTag(64);
        output.WriteBool(UseVideos);
      }
      if (TaskDescription.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(TaskDescription);
      }
      if (DatasetName.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(DatasetName);
      }
      if (Resume != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(Resume);
      }
      if (PushToHub != false) {
        output.WriteRawTag(160, 1);
        output.WriteBool(PushToHub);
      }
      if (Offline != false) {
        output.WriteRawTag(168, 1);
        output.WriteBool(Offline);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Robot != global::Data.Acquisition.Robot.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Robot);
      }
      if (SessionName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionName);
      }
      if (NbEpisodesGoal != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NbEpisodesGoal);
      }
      if (EpisodeDuration != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(EpisodeDuration);
      }
      if (BreakTimeDuration != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(BreakTimeDuration);
      }
      if (WarmupTimeDuration != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(WarmupTimeDuration);
      }
      if (HasFps) {
        output.WriteRawTag(56);
        output.WriteInt32(Fps);
      }
      if (UseVideos != false) {
        output.WriteRawTag(64);
        output.WriteBool(UseVideos);
      }
      if (TaskDescription.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(TaskDescription);
      }
      if (DatasetName.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(DatasetName);
      }
      if (Resume != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(Resume);
      }
      if (PushToHub != false) {
        output.WriteRawTag(160, 1);
        output.WriteBool(PushToHub);
      }
      if (Offline != false) {
        output.WriteRawTag(168, 1);
        output.WriteBool(Offline);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Robot != global::Data.Acquisition.Robot.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Robot);
      }
      if (SessionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionName);
      }
      if (NbEpisodesGoal != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NbEpisodesGoal);
      }
      if (EpisodeDuration != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EpisodeDuration);
      }
      if (BreakTimeDuration != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BreakTimeDuration);
      }
      if (WarmupTimeDuration != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WarmupTimeDuration);
      }
      if (HasFps) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Fps);
      }
      if (UseVideos != false) {
        size += 1 + 1;
      }
      if (TaskDescription.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskDescription);
      }
      if (DatasetName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DatasetName);
      }
      if (Resume != false) {
        size += 2 + 1;
      }
      if (PushToHub != false) {
        size += 2 + 1;
      }
      if (Offline != false) {
        size += 2 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SessionParams other) {
      if (other == null) {
        return;
      }
      if (other.Robot != global::Data.Acquisition.Robot.None) {
        Robot = other.Robot;
      }
      if (other.SessionName.Length != 0) {
        SessionName = other.SessionName;
      }
      if (other.NbEpisodesGoal != 0) {
        NbEpisodesGoal = other.NbEpisodesGoal;
      }
      if (other.EpisodeDuration != 0) {
        EpisodeDuration = other.EpisodeDuration;
      }
      if (other.BreakTimeDuration != 0) {
        BreakTimeDuration = other.BreakTimeDuration;
      }
      if (other.WarmupTimeDuration != 0) {
        WarmupTimeDuration = other.WarmupTimeDuration;
      }
      if (other.HasFps) {
        Fps = other.Fps;
      }
      if (other.UseVideos != false) {
        UseVideos = other.UseVideos;
      }
      if (other.TaskDescription.Length != 0) {
        TaskDescription = other.TaskDescription;
      }
      if (other.DatasetName.Length != 0) {
        DatasetName = other.DatasetName;
      }
      if (other.Resume != false) {
        Resume = other.Resume;
      }
      if (other.PushToHub != false) {
        PushToHub = other.PushToHub;
      }
      if (other.Offline != false) {
        Offline = other.Offline;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Robot = (global::Data.Acquisition.Robot) input.ReadEnum();
            break;
          }
          case 18: {
            SessionName = input.ReadString();
            break;
          }
          case 24: {
            NbEpisodesGoal = input.ReadInt32();
            break;
          }
          case 32: {
            EpisodeDuration = input.ReadInt32();
            break;
          }
          case 40: {
            BreakTimeDuration = input.ReadInt32();
            break;
          }
          case 48: {
            WarmupTimeDuration = input.ReadInt32();
            break;
          }
          case 56: {
            Fps = input.ReadInt32();
            break;
          }
          case 64: {
            UseVideos = input.ReadBool();
            break;
          }
          case 82: {
            TaskDescription = input.ReadString();
            break;
          }
          case 122: {
            DatasetName = input.ReadString();
            break;
          }
          case 128: {
            Resume = input.ReadBool();
            break;
          }
          case 160: {
            PushToHub = input.ReadBool();
            break;
          }
          case 168: {
            Offline = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Robot = (global::Data.Acquisition.Robot) input.ReadEnum();
            break;
          }
          case 18: {
            SessionName = input.ReadString();
            break;
          }
          case 24: {
            NbEpisodesGoal = input.ReadInt32();
            break;
          }
          case 32: {
            EpisodeDuration = input.ReadInt32();
            break;
          }
          case 40: {
            BreakTimeDuration = input.ReadInt32();
            break;
          }
          case 48: {
            WarmupTimeDuration = input.ReadInt32();
            break;
          }
          case 56: {
            Fps = input.ReadInt32();
            break;
          }
          case 64: {
            UseVideos = input.ReadBool();
            break;
          }
          case 82: {
            TaskDescription = input.ReadString();
            break;
          }
          case 122: {
            DatasetName = input.ReadString();
            break;
          }
          case 128: {
            Resume = input.ReadBool();
            break;
          }
          case 160: {
            PushToHub = input.ReadBool();
            break;
          }
          case 168: {
            Offline = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Session : pb::IMessage<Session>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Session> _parser = new pb::MessageParser<Session>(() => new Session());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Session> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Session() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Session(Session other) : this() {
      sessionName_ = other.sessionName_;
      nbEpisodesRecorded_ = other.nbEpisodesRecorded_;
      lastUpdate_ = other.lastUpdate_ != null ? other.lastUpdate_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Session Clone() {
      return new Session(this);
    }

    /// <summary>Field number for the "session_name" field.</summary>
    public const int SessionNameFieldNumber = 1;
    private string sessionName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionName {
      get { return sessionName_; }
      set {
        sessionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nb_episodes_recorded" field.</summary>
    public const int NbEpisodesRecordedFieldNumber = 2;
    private int nbEpisodesRecorded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NbEpisodesRecorded {
      get { return nbEpisodesRecorded_; }
      set {
        nbEpisodesRecorded_ = value;
      }
    }

    /// <summary>Field number for the "last_update" field.</summary>
    public const int LastUpdateFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastUpdate {
      get { return lastUpdate_; }
      set {
        lastUpdate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Session);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Session other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SessionName != other.SessionName) return false;
      if (NbEpisodesRecorded != other.NbEpisodesRecorded) return false;
      if (!object.Equals(LastUpdate, other.LastUpdate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SessionName.Length != 0) hash ^= SessionName.GetHashCode();
      if (NbEpisodesRecorded != 0) hash ^= NbEpisodesRecorded.GetHashCode();
      if (lastUpdate_ != null) hash ^= LastUpdate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SessionName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionName);
      }
      if (NbEpisodesRecorded != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NbEpisodesRecorded);
      }
      if (lastUpdate_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LastUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SessionName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionName);
      }
      if (NbEpisodesRecorded != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NbEpisodesRecorded);
      }
      if (lastUpdate_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LastUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SessionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionName);
      }
      if (NbEpisodesRecorded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NbEpisodesRecorded);
      }
      if (lastUpdate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Session other) {
      if (other == null) {
        return;
      }
      if (other.SessionName.Length != 0) {
        SessionName = other.SessionName;
      }
      if (other.NbEpisodesRecorded != 0) {
        NbEpisodesRecorded = other.NbEpisodesRecorded;
      }
      if (other.lastUpdate_ != null) {
        if (lastUpdate_ == null) {
          LastUpdate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastUpdate.MergeFrom(other.LastUpdate);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SessionName = input.ReadString();
            break;
          }
          case 16: {
            NbEpisodesRecorded = input.ReadInt32();
            break;
          }
          case 26: {
            if (lastUpdate_ == null) {
              LastUpdate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastUpdate);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SessionName = input.ReadString();
            break;
          }
          case 16: {
            NbEpisodesRecorded = input.ReadInt32();
            break;
          }
          case 26: {
            if (lastUpdate_ == null) {
              LastUpdate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastUpdate);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Dataset : pb::IMessage<Dataset>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Dataset> _parser = new pb::MessageParser<Dataset>(() => new Dataset());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Dataset> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dataset() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dataset(Dataset other) : this() {
      datasetName_ = other.datasetName_;
      pushed_ = other.pushed_;
      nbEpisodes_ = other.nbEpisodes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Dataset Clone() {
      return new Dataset(this);
    }

    /// <summary>Field number for the "dataset_name" field.</summary>
    public const int DatasetNameFieldNumber = 1;
    private string datasetName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DatasetName {
      get { return datasetName_; }
      set {
        datasetName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pushed" field.</summary>
    public const int PushedFieldNumber = 2;
    private global::Data.Acquisition.DatasetPushState pushed_ = global::Data.Acquisition.DatasetPushState.LocalOnly;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Data.Acquisition.DatasetPushState Pushed {
      get { return pushed_; }
      set {
        pushed_ = value;
      }
    }

    /// <summary>Field number for the "nb_episodes" field.</summary>
    public const int NbEpisodesFieldNumber = 3;
    private int nbEpisodes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NbEpisodes {
      get { return nbEpisodes_; }
      set {
        nbEpisodes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Dataset);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Dataset other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DatasetName != other.DatasetName) return false;
      if (Pushed != other.Pushed) return false;
      if (NbEpisodes != other.NbEpisodes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DatasetName.Length != 0) hash ^= DatasetName.GetHashCode();
      if (Pushed != global::Data.Acquisition.DatasetPushState.LocalOnly) hash ^= Pushed.GetHashCode();
      if (NbEpisodes != 0) hash ^= NbEpisodes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DatasetName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DatasetName);
      }
      if (Pushed != global::Data.Acquisition.DatasetPushState.LocalOnly) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Pushed);
      }
      if (NbEpisodes != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NbEpisodes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DatasetName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DatasetName);
      }
      if (Pushed != global::Data.Acquisition.DatasetPushState.LocalOnly) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Pushed);
      }
      if (NbEpisodes != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NbEpisodes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DatasetName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DatasetName);
      }
      if (Pushed != global::Data.Acquisition.DatasetPushState.LocalOnly) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Pushed);
      }
      if (NbEpisodes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NbEpisodes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Dataset other) {
      if (other == null) {
        return;
      }
      if (other.DatasetName.Length != 0) {
        DatasetName = other.DatasetName;
      }
      if (other.Pushed != global::Data.Acquisition.DatasetPushState.LocalOnly) {
        Pushed = other.Pushed;
      }
      if (other.NbEpisodes != 0) {
        NbEpisodes = other.NbEpisodes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DatasetName = input.ReadString();
            break;
          }
          case 16: {
            Pushed = (global::Data.Acquisition.DatasetPushState) input.ReadEnum();
            break;
          }
          case 24: {
            NbEpisodes = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DatasetName = input.ReadString();
            break;
          }
          case 16: {
            Pushed = (global::Data.Acquisition.DatasetPushState) input.ReadEnum();
            break;
          }
          case 24: {
            NbEpisodes = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DatasetList : pb::IMessage<DatasetList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DatasetList> _parser = new pb::MessageParser<DatasetList>(() => new DatasetList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DatasetList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetList(DatasetList other) : this() {
      datasets_ = other.datasets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DatasetList Clone() {
      return new DatasetList(this);
    }

    /// <summary>Field number for the "datasets" field.</summary>
    public const int DatasetsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Data.Acquisition.Dataset> _repeated_datasets_codec
        = pb::FieldCodec.ForMessage(10, global::Data.Acquisition.Dataset.Parser);
    private readonly pbc::RepeatedField<global::Data.Acquisition.Dataset> datasets_ = new pbc::RepeatedField<global::Data.Acquisition.Dataset>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Data.Acquisition.Dataset> Datasets {
      get { return datasets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DatasetList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DatasetList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!datasets_.Equals(other.datasets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= datasets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      datasets_.WriteTo(output, _repeated_datasets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      datasets_.WriteTo(ref output, _repeated_datasets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += datasets_.CalculateSize(_repeated_datasets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DatasetList other) {
      if (other == null) {
        return;
      }
      datasets_.Add(other.datasets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            datasets_.AddEntriesFrom(input, _repeated_datasets_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            datasets_.AddEntriesFrom(ref input, _repeated_datasets_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActionAck : pb::IMessage<ActionAck>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionAck> _parser = new pb::MessageParser<ActionAck>(() => new ActionAck());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionAck> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionAck() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionAck(ActionAck other) : this() {
      successAck_ = other.successAck_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionAck Clone() {
      return new ActionAck(this);
    }

    /// <summary>Field number for the "success_ack" field.</summary>
    public const int SuccessAckFieldNumber = 1;
    private bool successAck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SuccessAck {
      get { return successAck_; }
      set {
        successAck_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionAck);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionAck other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SuccessAck != other.SuccessAck) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SuccessAck != false) hash ^= SuccessAck.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SuccessAck != false) {
        output.WriteRawTag(8);
        output.WriteBool(SuccessAck);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SuccessAck != false) {
        output.WriteRawTag(8);
        output.WriteBool(SuccessAck);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SuccessAck != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionAck other) {
      if (other == null) {
        return;
      }
      if (other.SuccessAck != false) {
        SuccessAck = other.SuccessAck;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SuccessAck = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SuccessAck = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EpisodeRating : pb::IMessage<EpisodeRating>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EpisodeRating> _parser = new pb::MessageParser<EpisodeRating>(() => new EpisodeRating());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EpisodeRating> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EpisodeRating() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EpisodeRating(EpisodeRating other) : this() {
      success_ = other.success_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EpisodeRating Clone() {
      return new EpisodeRating(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EpisodeRating);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EpisodeRating other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EpisodeRating other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Episode : pb::IMessage<Episode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Episode> _parser = new pb::MessageParser<Episode>(() => new Episode());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Episode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Episode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Episode(Episode other) : this() {
      _hasBits0 = other._hasBits0;
      episodeId_ = other.episodeId_;
      duration_ = other.duration_;
      episodeSuccess_ = other.episodeSuccess_;
      description_ = other.description_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Episode Clone() {
      return new Episode(this);
    }

    /// <summary>Field number for the "episode_id" field.</summary>
    public const int EpisodeIdFieldNumber = 1;
    private readonly static int EpisodeIdDefaultValue = 0;

    private int episodeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EpisodeId {
      get { if ((_hasBits0 & 1) != 0) { return episodeId_; } else { return EpisodeIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        episodeId_ = value;
      }
    }
    /// <summary>Gets whether the "episode_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEpisodeId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "episode_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEpisodeId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 2;
    private int duration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Duration {
      get { return duration_; }
      set {
        duration_ = value;
      }
    }

    /// <summary>Field number for the "episode_success" field.</summary>
    public const int EpisodeSuccessFieldNumber = 3;
    private bool episodeSuccess_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EpisodeSuccess {
      get { return episodeSuccess_; }
      set {
        episodeSuccess_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 4;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Episode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Episode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EpisodeId != other.EpisodeId) return false;
      if (Duration != other.Duration) return false;
      if (EpisodeSuccess != other.EpisodeSuccess) return false;
      if (Description != other.Description) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEpisodeId) hash ^= EpisodeId.GetHashCode();
      if (Duration != 0) hash ^= Duration.GetHashCode();
      if (EpisodeSuccess != false) hash ^= EpisodeSuccess.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEpisodeId) {
        output.WriteRawTag(8);
        output.WriteInt32(EpisodeId);
      }
      if (Duration != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Duration);
      }
      if (EpisodeSuccess != false) {
        output.WriteRawTag(24);
        output.WriteBool(EpisodeSuccess);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEpisodeId) {
        output.WriteRawTag(8);
        output.WriteInt32(EpisodeId);
      }
      if (Duration != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Duration);
      }
      if (EpisodeSuccess != false) {
        output.WriteRawTag(24);
        output.WriteBool(EpisodeSuccess);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEpisodeId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EpisodeId);
      }
      if (Duration != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Duration);
      }
      if (EpisodeSuccess != false) {
        size += 1 + 1;
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Episode other) {
      if (other == null) {
        return;
      }
      if (other.HasEpisodeId) {
        EpisodeId = other.EpisodeId;
      }
      if (other.Duration != 0) {
        Duration = other.Duration;
      }
      if (other.EpisodeSuccess != false) {
        EpisodeSuccess = other.EpisodeSuccess;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EpisodeId = input.ReadInt32();
            break;
          }
          case 16: {
            Duration = input.ReadInt32();
            break;
          }
          case 24: {
            EpisodeSuccess = input.ReadBool();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EpisodeId = input.ReadInt32();
            break;
          }
          case 16: {
            Duration = input.ReadInt32();
            break;
          }
          case 24: {
            EpisodeSuccess = input.ReadBool();
            break;
          }
          case 34: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Login : pb::IMessage<Login>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Login> _parser = new pb::MessageParser<Login>(() => new Login());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Login> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Login() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Login(Login other) : this() {
      token_ = other.token_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Login Clone() {
      return new Login(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Login);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Login other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Login other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
