// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data-acquisition.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Data.Acquisition {
  public static partial class DataAcquisitionService
  {
    static readonly string __ServiceName = "data.acquisition.DataAcquisitionService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Data.Acquisition.DatasetList> __Marshaller_data_acquisition_DatasetList = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Data.Acquisition.DatasetList.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Data.Acquisition.Dataset> __Marshaller_data_acquisition_Dataset = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Data.Acquisition.Dataset.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Data.Acquisition.ActionAck> __Marshaller_data_acquisition_ActionAck = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Data.Acquisition.ActionAck.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Data.Acquisition.SessionParams> __Marshaller_data_acquisition_SessionParams = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Data.Acquisition.SessionParams.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Data.Acquisition.EpisodeRating> __Marshaller_data_acquisition_EpisodeRating = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Data.Acquisition.EpisodeRating.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.DatasetList> __Method_GetDatasetList = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.DatasetList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDatasetList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_data_acquisition_DatasetList);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck> __Method_AddDataset = new grpc::Method<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddDataset",
        __Marshaller_data_acquisition_Dataset,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck> __Method_RemoveDataset = new grpc::Method<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveDataset",
        __Marshaller_data_acquisition_Dataset,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck> __Method_UpdateDataset = new grpc::Method<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateDataset",
        __Marshaller_data_acquisition_Dataset,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck> __Method_ClearAllDatasets = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ClearAllDatasets",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Data.Acquisition.SessionParams, global::Data.Acquisition.ActionAck> __Method_StartSession = new grpc::Method<global::Data.Acquisition.SessionParams, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartSession",
        __Marshaller_data_acquisition_SessionParams,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck> __Method_StopSession = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopSession",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck> __Method_StartEpisode = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartEpisode",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck> __Method_StopEpisode = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopEpisode",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Data.Acquisition.EpisodeRating, global::Data.Acquisition.ActionAck> __Method_SaveEpisode = new grpc::Method<global::Data.Acquisition.EpisodeRating, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveEpisode",
        __Marshaller_data_acquisition_EpisodeRating,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck> __Method_UploadSession = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UploadSession",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Data.Acquisition.SessionParams, global::Data.Acquisition.ActionAck> __Method_RemoveSession = new grpc::Method<global::Data.Acquisition.SessionParams, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveSession",
        __Marshaller_data_acquisition_SessionParams,
        __Marshaller_data_acquisition_ActionAck);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck> __Method_ClearAllSessions = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ClearAllSessions",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_data_acquisition_ActionAck);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Data.Acquisition.DataAcquisitionReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DataAcquisitionService</summary>
    [grpc::BindServiceMethod(typeof(DataAcquisitionService), "BindService")]
    public abstract partial class DataAcquisitionServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.DatasetList> GetDatasetList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> AddDataset(global::Data.Acquisition.Dataset request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> RemoveDataset(global::Data.Acquisition.Dataset request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> UpdateDataset(global::Data.Acquisition.Dataset request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> ClearAllDatasets(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> StartSession(global::Data.Acquisition.SessionParams request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> StopSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> StartEpisode(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> StopEpisode(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> SaveEpisode(global::Data.Acquisition.EpisodeRating request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> UploadSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> RemoveSession(global::Data.Acquisition.SessionParams request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Data.Acquisition.ActionAck> ClearAllSessions(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DataAcquisitionService</summary>
    public partial class DataAcquisitionServiceClient : grpc::ClientBase<DataAcquisitionServiceClient>
    {
      /// <summary>Creates a new client for DataAcquisitionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DataAcquisitionServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DataAcquisitionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DataAcquisitionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DataAcquisitionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DataAcquisitionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.DatasetList GetDatasetList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDatasetList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.DatasetList GetDatasetList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDatasetList, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.DatasetList> GetDatasetListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDatasetListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.DatasetList> GetDatasetListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDatasetList, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck AddDataset(global::Data.Acquisition.Dataset request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddDataset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck AddDataset(global::Data.Acquisition.Dataset request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddDataset, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> AddDatasetAsync(global::Data.Acquisition.Dataset request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddDatasetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> AddDatasetAsync(global::Data.Acquisition.Dataset request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddDataset, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck RemoveDataset(global::Data.Acquisition.Dataset request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveDataset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck RemoveDataset(global::Data.Acquisition.Dataset request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveDataset, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> RemoveDatasetAsync(global::Data.Acquisition.Dataset request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveDatasetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> RemoveDatasetAsync(global::Data.Acquisition.Dataset request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveDataset, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck UpdateDataset(global::Data.Acquisition.Dataset request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateDataset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck UpdateDataset(global::Data.Acquisition.Dataset request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateDataset, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> UpdateDatasetAsync(global::Data.Acquisition.Dataset request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateDatasetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> UpdateDatasetAsync(global::Data.Acquisition.Dataset request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateDataset, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck ClearAllDatasets(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ClearAllDatasets(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck ClearAllDatasets(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ClearAllDatasets, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> ClearAllDatasetsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ClearAllDatasetsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> ClearAllDatasetsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ClearAllDatasets, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck StartSession(global::Data.Acquisition.SessionParams request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartSession(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck StartSession(global::Data.Acquisition.SessionParams request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartSession, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> StartSessionAsync(global::Data.Acquisition.SessionParams request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartSessionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> StartSessionAsync(global::Data.Acquisition.SessionParams request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartSession, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck StopSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopSession(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck StopSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StopSession, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> StopSessionAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopSessionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> StopSessionAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StopSession, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck StartEpisode(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartEpisode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck StartEpisode(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartEpisode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> StartEpisodeAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartEpisodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> StartEpisodeAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartEpisode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck StopEpisode(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopEpisode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck StopEpisode(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StopEpisode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> StopEpisodeAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopEpisodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> StopEpisodeAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StopEpisode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck SaveEpisode(global::Data.Acquisition.EpisodeRating request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveEpisode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck SaveEpisode(global::Data.Acquisition.EpisodeRating request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveEpisode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> SaveEpisodeAsync(global::Data.Acquisition.EpisodeRating request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveEpisodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> SaveEpisodeAsync(global::Data.Acquisition.EpisodeRating request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveEpisode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck UploadSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadSession(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck UploadSession(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UploadSession, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> UploadSessionAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadSessionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> UploadSessionAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UploadSession, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck RemoveSession(global::Data.Acquisition.SessionParams request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveSession(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck RemoveSession(global::Data.Acquisition.SessionParams request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveSession, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> RemoveSessionAsync(global::Data.Acquisition.SessionParams request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveSessionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> RemoveSessionAsync(global::Data.Acquisition.SessionParams request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveSession, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck ClearAllSessions(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ClearAllSessions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Data.Acquisition.ActionAck ClearAllSessions(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ClearAllSessions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> ClearAllSessionsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ClearAllSessionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Data.Acquisition.ActionAck> ClearAllSessionsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ClearAllSessions, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DataAcquisitionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DataAcquisitionServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DataAcquisitionServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetDatasetList, serviceImpl.GetDatasetList)
          .AddMethod(__Method_AddDataset, serviceImpl.AddDataset)
          .AddMethod(__Method_RemoveDataset, serviceImpl.RemoveDataset)
          .AddMethod(__Method_UpdateDataset, serviceImpl.UpdateDataset)
          .AddMethod(__Method_ClearAllDatasets, serviceImpl.ClearAllDatasets)
          .AddMethod(__Method_StartSession, serviceImpl.StartSession)
          .AddMethod(__Method_StopSession, serviceImpl.StopSession)
          .AddMethod(__Method_StartEpisode, serviceImpl.StartEpisode)
          .AddMethod(__Method_StopEpisode, serviceImpl.StopEpisode)
          .AddMethod(__Method_SaveEpisode, serviceImpl.SaveEpisode)
          .AddMethod(__Method_UploadSession, serviceImpl.UploadSession)
          .AddMethod(__Method_RemoveSession, serviceImpl.RemoveSession)
          .AddMethod(__Method_ClearAllSessions, serviceImpl.ClearAllSessions).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DataAcquisitionServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetDatasetList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.DatasetList>(serviceImpl.GetDatasetList));
      serviceBinder.AddMethod(__Method_AddDataset, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck>(serviceImpl.AddDataset));
      serviceBinder.AddMethod(__Method_RemoveDataset, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck>(serviceImpl.RemoveDataset));
      serviceBinder.AddMethod(__Method_UpdateDataset, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Data.Acquisition.Dataset, global::Data.Acquisition.ActionAck>(serviceImpl.UpdateDataset));
      serviceBinder.AddMethod(__Method_ClearAllDatasets, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(serviceImpl.ClearAllDatasets));
      serviceBinder.AddMethod(__Method_StartSession, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Data.Acquisition.SessionParams, global::Data.Acquisition.ActionAck>(serviceImpl.StartSession));
      serviceBinder.AddMethod(__Method_StopSession, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(serviceImpl.StopSession));
      serviceBinder.AddMethod(__Method_StartEpisode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(serviceImpl.StartEpisode));
      serviceBinder.AddMethod(__Method_StopEpisode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(serviceImpl.StopEpisode));
      serviceBinder.AddMethod(__Method_SaveEpisode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Data.Acquisition.EpisodeRating, global::Data.Acquisition.ActionAck>(serviceImpl.SaveEpisode));
      serviceBinder.AddMethod(__Method_UploadSession, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(serviceImpl.UploadSession));
      serviceBinder.AddMethod(__Method_RemoveSession, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Data.Acquisition.SessionParams, global::Data.Acquisition.ActionAck>(serviceImpl.RemoveSession));
      serviceBinder.AddMethod(__Method_ClearAllSessions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Data.Acquisition.ActionAck>(serviceImpl.ClearAllSessions));
    }

  }
}
#endregion
