// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: teleoperator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Data.Acquisition.Teleoperator {

  /// <summary>Holder for reflection information generated from teleoperator.proto</summary>
  public static partial class TeleoperatorReflection {

    #region Descriptor
    /// <summary>File descriptor for teleoperator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TeleoperatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJ0ZWxlb3BlcmF0b3IucHJvdG8SHWRhdGEuYWNxdWlzaXRpb24udGVsZW9w",
            "ZXJhdG9yIrEBCgxUZWxlb3BlcmF0b3ISSgoRdGVsZW9wZXJhdG9yX3R5cGUY",
            "ASABKA4yLy5kYXRhLmFjcXVpc2l0aW9uLnRlbGVvcGVyYXRvci5UZWxlb3Bl",
            "cmF0b3JUeXBlEkUKB3JlYWNoeTIYAyABKAsyMi5kYXRhLmFjcXVpc2l0aW9u",
            "LnRlbGVvcGVyYXRvci5SZWFjaHkyVGVsZW9wZXJhdG9ySABCDgoMdGVsZW9w",
            "ZXJhdG9yIr0CChNSZWFjaHkyVGVsZW9wZXJhdG9yEhIKCmlwX2FkZHJlc3MY",
            "ASABKAkSIQoUdXNlX3ByZXNlbnRfcG9zaXRpb24YAiABKAhIAIgBARIdChB3",
            "aXRoX21vYmlsZV9iYXNlGAMgASgISAGIAQESFwoKd2l0aF9sX2FybRgEIAEo",
            "CEgCiAEBEhcKCndpdGhfcl9hcm0YBSABKAhIA4gBARIWCgl3aXRoX25lY2sY",
            "BiABKAhIBIgBARIaCg13aXRoX2FudGVubmFzGAcgASgISAWIAQFCFwoVX3Vz",
            "ZV9wcmVzZW50X3Bvc2l0aW9uQhMKEV93aXRoX21vYmlsZV9iYXNlQg0KC193",
            "aXRoX2xfYXJtQg0KC193aXRoX3JfYXJtQgwKCl93aXRoX25lY2tCEAoOX3dp",
            "dGhfYW50ZW5uYXMqNgoQVGVsZW9wZXJhdG9yVHlwZRIVChFURUxFT1BFUkFU",
            "T1JfTk9ORRAAEgsKB1JFQUNIWTIQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Data.Acquisition.Teleoperator.TeleoperatorType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.Teleoperator.Teleoperator), global::Data.Acquisition.Teleoperator.Teleoperator.Parser, new[]{ "TeleoperatorType", "Reachy2" }, new[]{ "Teleoperator" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Data.Acquisition.Teleoperator.Reachy2Teleoperator), global::Data.Acquisition.Teleoperator.Reachy2Teleoperator.Parser, new[]{ "IpAddress", "UsePresentPosition", "WithMobileBase", "WithLArm", "WithRArm", "WithNeck", "WithAntennas" }, new[]{ "UsePresentPosition", "WithMobileBase", "WithLArm", "WithRArm", "WithNeck", "WithAntennas" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TeleoperatorType {
    [pbr::OriginalName("TELEOPERATOR_NONE")] TeleoperatorNone = 0,
    [pbr::OriginalName("REACHY2")] Reachy2 = 1,
  }

  #endregion

  #region Messages
  public sealed partial class Teleoperator : pb::IMessage<Teleoperator>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Teleoperator> _parser = new pb::MessageParser<Teleoperator>(() => new Teleoperator());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Teleoperator> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.Teleoperator.TeleoperatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Teleoperator() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Teleoperator(Teleoperator other) : this() {
      teleoperatorType_ = other.teleoperatorType_;
      switch (other.TeleoperatorCase) {
        case TeleoperatorOneofCase.Reachy2:
          Reachy2 = other.Reachy2.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Teleoperator Clone() {
      return new Teleoperator(this);
    }

    /// <summary>Field number for the "teleoperator_type" field.</summary>
    public const int TeleoperatorTypeFieldNumber = 1;
    private global::Data.Acquisition.Teleoperator.TeleoperatorType teleoperatorType_ = global::Data.Acquisition.Teleoperator.TeleoperatorType.TeleoperatorNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Data.Acquisition.Teleoperator.TeleoperatorType TeleoperatorType {
      get { return teleoperatorType_; }
      set {
        teleoperatorType_ = value;
      }
    }

    /// <summary>Field number for the "reachy2" field.</summary>
    public const int Reachy2FieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Data.Acquisition.Teleoperator.Reachy2Teleoperator Reachy2 {
      get { return teleoperatorCase_ == TeleoperatorOneofCase.Reachy2 ? (global::Data.Acquisition.Teleoperator.Reachy2Teleoperator) teleoperator_ : null; }
      set {
        teleoperator_ = value;
        teleoperatorCase_ = value == null ? TeleoperatorOneofCase.None : TeleoperatorOneofCase.Reachy2;
      }
    }

    private object teleoperator_;
    /// <summary>Enum of possible cases for the "teleoperator" oneof.</summary>
    public enum TeleoperatorOneofCase {
      None = 0,
      Reachy2 = 3,
    }
    private TeleoperatorOneofCase teleoperatorCase_ = TeleoperatorOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeleoperatorOneofCase TeleoperatorCase {
      get { return teleoperatorCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTeleoperator() {
      teleoperatorCase_ = TeleoperatorOneofCase.None;
      teleoperator_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Teleoperator);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Teleoperator other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TeleoperatorType != other.TeleoperatorType) return false;
      if (!object.Equals(Reachy2, other.Reachy2)) return false;
      if (TeleoperatorCase != other.TeleoperatorCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TeleoperatorType != global::Data.Acquisition.Teleoperator.TeleoperatorType.TeleoperatorNone) hash ^= TeleoperatorType.GetHashCode();
      if (teleoperatorCase_ == TeleoperatorOneofCase.Reachy2) hash ^= Reachy2.GetHashCode();
      hash ^= (int) teleoperatorCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TeleoperatorType != global::Data.Acquisition.Teleoperator.TeleoperatorType.TeleoperatorNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TeleoperatorType);
      }
      if (teleoperatorCase_ == TeleoperatorOneofCase.Reachy2) {
        output.WriteRawTag(26);
        output.WriteMessage(Reachy2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TeleoperatorType != global::Data.Acquisition.Teleoperator.TeleoperatorType.TeleoperatorNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TeleoperatorType);
      }
      if (teleoperatorCase_ == TeleoperatorOneofCase.Reachy2) {
        output.WriteRawTag(26);
        output.WriteMessage(Reachy2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TeleoperatorType != global::Data.Acquisition.Teleoperator.TeleoperatorType.TeleoperatorNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TeleoperatorType);
      }
      if (teleoperatorCase_ == TeleoperatorOneofCase.Reachy2) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reachy2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Teleoperator other) {
      if (other == null) {
        return;
      }
      if (other.TeleoperatorType != global::Data.Acquisition.Teleoperator.TeleoperatorType.TeleoperatorNone) {
        TeleoperatorType = other.TeleoperatorType;
      }
      switch (other.TeleoperatorCase) {
        case TeleoperatorOneofCase.Reachy2:
          if (Reachy2 == null) {
            Reachy2 = new global::Data.Acquisition.Teleoperator.Reachy2Teleoperator();
          }
          Reachy2.MergeFrom(other.Reachy2);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TeleoperatorType = (global::Data.Acquisition.Teleoperator.TeleoperatorType) input.ReadEnum();
            break;
          }
          case 26: {
            global::Data.Acquisition.Teleoperator.Reachy2Teleoperator subBuilder = new global::Data.Acquisition.Teleoperator.Reachy2Teleoperator();
            if (teleoperatorCase_ == TeleoperatorOneofCase.Reachy2) {
              subBuilder.MergeFrom(Reachy2);
            }
            input.ReadMessage(subBuilder);
            Reachy2 = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TeleoperatorType = (global::Data.Acquisition.Teleoperator.TeleoperatorType) input.ReadEnum();
            break;
          }
          case 26: {
            global::Data.Acquisition.Teleoperator.Reachy2Teleoperator subBuilder = new global::Data.Acquisition.Teleoperator.Reachy2Teleoperator();
            if (teleoperatorCase_ == TeleoperatorOneofCase.Reachy2) {
              subBuilder.MergeFrom(Reachy2);
            }
            input.ReadMessage(subBuilder);
            Reachy2 = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Reachy2Teleoperator : pb::IMessage<Reachy2Teleoperator>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Reachy2Teleoperator> _parser = new pb::MessageParser<Reachy2Teleoperator>(() => new Reachy2Teleoperator());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Reachy2Teleoperator> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Data.Acquisition.Teleoperator.TeleoperatorReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reachy2Teleoperator() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reachy2Teleoperator(Reachy2Teleoperator other) : this() {
      _hasBits0 = other._hasBits0;
      ipAddress_ = other.ipAddress_;
      usePresentPosition_ = other.usePresentPosition_;
      withMobileBase_ = other.withMobileBase_;
      withLArm_ = other.withLArm_;
      withRArm_ = other.withRArm_;
      withNeck_ = other.withNeck_;
      withAntennas_ = other.withAntennas_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reachy2Teleoperator Clone() {
      return new Reachy2Teleoperator(this);
    }

    /// <summary>Field number for the "ip_address" field.</summary>
    public const int IpAddressFieldNumber = 1;
    private string ipAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IpAddress {
      get { return ipAddress_; }
      set {
        ipAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "use_present_position" field.</summary>
    public const int UsePresentPositionFieldNumber = 2;
    private readonly static bool UsePresentPositionDefaultValue = false;

    private bool usePresentPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UsePresentPosition {
      get { if ((_hasBits0 & 1) != 0) { return usePresentPosition_; } else { return UsePresentPositionDefaultValue; } }
      set {
        _hasBits0 |= 1;
        usePresentPosition_ = value;
      }
    }
    /// <summary>Gets whether the "use_present_position" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUsePresentPosition {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "use_present_position" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUsePresentPosition() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "with_mobile_base" field.</summary>
    public const int WithMobileBaseFieldNumber = 3;
    private readonly static bool WithMobileBaseDefaultValue = false;

    private bool withMobileBase_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool WithMobileBase {
      get { if ((_hasBits0 & 2) != 0) { return withMobileBase_; } else { return WithMobileBaseDefaultValue; } }
      set {
        _hasBits0 |= 2;
        withMobileBase_ = value;
      }
    }
    /// <summary>Gets whether the "with_mobile_base" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWithMobileBase {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "with_mobile_base" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWithMobileBase() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "with_l_arm" field.</summary>
    public const int WithLArmFieldNumber = 4;
    private readonly static bool WithLArmDefaultValue = false;

    private bool withLArm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool WithLArm {
      get { if ((_hasBits0 & 4) != 0) { return withLArm_; } else { return WithLArmDefaultValue; } }
      set {
        _hasBits0 |= 4;
        withLArm_ = value;
      }
    }
    /// <summary>Gets whether the "with_l_arm" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWithLArm {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "with_l_arm" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWithLArm() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "with_r_arm" field.</summary>
    public const int WithRArmFieldNumber = 5;
    private readonly static bool WithRArmDefaultValue = false;

    private bool withRArm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool WithRArm {
      get { if ((_hasBits0 & 8) != 0) { return withRArm_; } else { return WithRArmDefaultValue; } }
      set {
        _hasBits0 |= 8;
        withRArm_ = value;
      }
    }
    /// <summary>Gets whether the "with_r_arm" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWithRArm {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "with_r_arm" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWithRArm() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "with_neck" field.</summary>
    public const int WithNeckFieldNumber = 6;
    private readonly static bool WithNeckDefaultValue = false;

    private bool withNeck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool WithNeck {
      get { if ((_hasBits0 & 16) != 0) { return withNeck_; } else { return WithNeckDefaultValue; } }
      set {
        _hasBits0 |= 16;
        withNeck_ = value;
      }
    }
    /// <summary>Gets whether the "with_neck" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWithNeck {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "with_neck" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWithNeck() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "with_antennas" field.</summary>
    public const int WithAntennasFieldNumber = 7;
    private readonly static bool WithAntennasDefaultValue = false;

    private bool withAntennas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool WithAntennas {
      get { if ((_hasBits0 & 32) != 0) { return withAntennas_; } else { return WithAntennasDefaultValue; } }
      set {
        _hasBits0 |= 32;
        withAntennas_ = value;
      }
    }
    /// <summary>Gets whether the "with_antennas" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWithAntennas {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "with_antennas" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWithAntennas() {
      _hasBits0 &= ~32;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Reachy2Teleoperator);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Reachy2Teleoperator other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IpAddress != other.IpAddress) return false;
      if (UsePresentPosition != other.UsePresentPosition) return false;
      if (WithMobileBase != other.WithMobileBase) return false;
      if (WithLArm != other.WithLArm) return false;
      if (WithRArm != other.WithRArm) return false;
      if (WithNeck != other.WithNeck) return false;
      if (WithAntennas != other.WithAntennas) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IpAddress.Length != 0) hash ^= IpAddress.GetHashCode();
      if (HasUsePresentPosition) hash ^= UsePresentPosition.GetHashCode();
      if (HasWithMobileBase) hash ^= WithMobileBase.GetHashCode();
      if (HasWithLArm) hash ^= WithLArm.GetHashCode();
      if (HasWithRArm) hash ^= WithRArm.GetHashCode();
      if (HasWithNeck) hash ^= WithNeck.GetHashCode();
      if (HasWithAntennas) hash ^= WithAntennas.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IpAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IpAddress);
      }
      if (HasUsePresentPosition) {
        output.WriteRawTag(16);
        output.WriteBool(UsePresentPosition);
      }
      if (HasWithMobileBase) {
        output.WriteRawTag(24);
        output.WriteBool(WithMobileBase);
      }
      if (HasWithLArm) {
        output.WriteRawTag(32);
        output.WriteBool(WithLArm);
      }
      if (HasWithRArm) {
        output.WriteRawTag(40);
        output.WriteBool(WithRArm);
      }
      if (HasWithNeck) {
        output.WriteRawTag(48);
        output.WriteBool(WithNeck);
      }
      if (HasWithAntennas) {
        output.WriteRawTag(56);
        output.WriteBool(WithAntennas);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IpAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IpAddress);
      }
      if (HasUsePresentPosition) {
        output.WriteRawTag(16);
        output.WriteBool(UsePresentPosition);
      }
      if (HasWithMobileBase) {
        output.WriteRawTag(24);
        output.WriteBool(WithMobileBase);
      }
      if (HasWithLArm) {
        output.WriteRawTag(32);
        output.WriteBool(WithLArm);
      }
      if (HasWithRArm) {
        output.WriteRawTag(40);
        output.WriteBool(WithRArm);
      }
      if (HasWithNeck) {
        output.WriteRawTag(48);
        output.WriteBool(WithNeck);
      }
      if (HasWithAntennas) {
        output.WriteRawTag(56);
        output.WriteBool(WithAntennas);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IpAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IpAddress);
      }
      if (HasUsePresentPosition) {
        size += 1 + 1;
      }
      if (HasWithMobileBase) {
        size += 1 + 1;
      }
      if (HasWithLArm) {
        size += 1 + 1;
      }
      if (HasWithRArm) {
        size += 1 + 1;
      }
      if (HasWithNeck) {
        size += 1 + 1;
      }
      if (HasWithAntennas) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Reachy2Teleoperator other) {
      if (other == null) {
        return;
      }
      if (other.IpAddress.Length != 0) {
        IpAddress = other.IpAddress;
      }
      if (other.HasUsePresentPosition) {
        UsePresentPosition = other.UsePresentPosition;
      }
      if (other.HasWithMobileBase) {
        WithMobileBase = other.WithMobileBase;
      }
      if (other.HasWithLArm) {
        WithLArm = other.WithLArm;
      }
      if (other.HasWithRArm) {
        WithRArm = other.WithRArm;
      }
      if (other.HasWithNeck) {
        WithNeck = other.WithNeck;
      }
      if (other.HasWithAntennas) {
        WithAntennas = other.WithAntennas;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IpAddress = input.ReadString();
            break;
          }
          case 16: {
            UsePresentPosition = input.ReadBool();
            break;
          }
          case 24: {
            WithMobileBase = input.ReadBool();
            break;
          }
          case 32: {
            WithLArm = input.ReadBool();
            break;
          }
          case 40: {
            WithRArm = input.ReadBool();
            break;
          }
          case 48: {
            WithNeck = input.ReadBool();
            break;
          }
          case 56: {
            WithAntennas = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IpAddress = input.ReadString();
            break;
          }
          case 16: {
            UsePresentPosition = input.ReadBool();
            break;
          }
          case 24: {
            WithMobileBase = input.ReadBool();
            break;
          }
          case 32: {
            WithLArm = input.ReadBool();
            break;
          }
          case 40: {
            WithRArm = input.ReadBool();
            break;
          }
          case 48: {
            WithNeck = input.ReadBool();
            break;
          }
          case 56: {
            WithAntennas = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
