// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: amazing-hand.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ah.Teleoperation {

  /// <summary>Holder for reflection information generated from amazing-hand.proto</summary>
  public static partial class AmazingHandReflection {

    #region Descriptor
    /// <summary>File descriptor for amazing-hand.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AmazingHandReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJhbWF6aW5nLWhhbmQucHJvdG8SEGFoLnRlbGVvcGVyYXRpb24aG2dvb2ds",
            "ZS9wcm90b2J1Zi9lbXB0eS5wcm90byJpCg9DYWxpYnJhdGlvbkRhdGESFAoM",
            "dGh1bWJfbGVuZ3RoGAEgASgCEhQKDGluZGV4X2xlbmd0aBgCIAEoAhIVCg1t",
            "aWRkbGVfbGVuZ3RoGAMgASgCEhMKC3JpbmdfbGVuZ3RoGAQgASgCIjQKEUZp",
            "bmdlclRpcFBvc2l0aW9uEgkKAXgYASABKAISCQoBeRgCIAEoAhIJCgF6GAMg",
            "ASgCImAKCVBpbmNoRGF0YRITCgtwaW5jaF92YWx1ZRgBIAEoAhI+ChFkaXN0",
            "YW5jZV90b190aHVtYhgCIAEoCzIjLmFoLnRlbGVvcGVyYXRpb24uRmluZ2Vy",
            "VGlwUG9zaXRpb24i+QIKEUhhbmRDb25maWd1cmF0aW9uEjIKBXRodW1iGAEg",
            "ASgLMiMuYWgudGVsZW9wZXJhdGlvbi5GaW5nZXJUaXBQb3NpdGlvbhIyCgVp",
            "bmRleBgCIAEoCzIjLmFoLnRlbGVvcGVyYXRpb24uRmluZ2VyVGlwUG9zaXRp",
            "b24SMwoGbWlkZGxlGAMgASgLMiMuYWgudGVsZW9wZXJhdGlvbi5GaW5nZXJU",
            "aXBQb3NpdGlvbhIxCgRyaW5nGAQgASgLMiMuYWgudGVsZW9wZXJhdGlvbi5G",
            "aW5nZXJUaXBQb3NpdGlvbhIwCgtpbmRleF9waW5jaBgGIAEoCzIbLmFoLnRl",
            "bGVvcGVyYXRpb24uUGluY2hEYXRhEjEKDG1pZGRsZV9waW5jaBgHIAEoCzIb",
            "LmFoLnRlbGVvcGVyYXRpb24uUGluY2hEYXRhEi8KCnJpbmdfcGluY2gYCCAB",
            "KAsyGy5haC50ZWxlb3BlcmF0aW9uLlBpbmNoRGF0YSKyAQoYSGFuZFRlbGVv",
            "cGVyYXRpb25Db21tYW5kEjsKCWxlZnRfaGFuZBgBIAEoCzIjLmFoLnRlbGVv",
            "cGVyYXRpb24uSGFuZENvbmZpZ3VyYXRpb25IAIgBARI8CgpyaWdodF9oYW5k",
            "GAIgASgLMiMuYWgudGVsZW9wZXJhdGlvbi5IYW5kQ29uZmlndXJhdGlvbkgB",
            "iAEBQgwKCl9sZWZ0X2hhbmRCDQoLX3JpZ2h0X2hhbmQywQEKFkFIVGVsZW9w",
            "ZXJhdGlvblNlcnZpY2USUAoTU2VuZENhbGlicmF0aW9uRGF0YRIhLmFoLnRl",
            "bGVvcGVyYXRpb24uQ2FsaWJyYXRpb25EYXRhGhYuZ29vZ2xlLnByb3RvYnVm",
            "LkVtcHR5ElUKD1NlbmRIYW5kQ29tbWFuZBIqLmFoLnRlbGVvcGVyYXRpb24u",
            "SGFuZFRlbGVvcGVyYXRpb25Db21tYW5kGhYuZ29vZ2xlLnByb3RvYnVmLkVt",
            "cHR5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ah.Teleoperation.CalibrationData), global::Ah.Teleoperation.CalibrationData.Parser, new[]{ "ThumbLength", "IndexLength", "MiddleLength", "RingLength" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ah.Teleoperation.FingerTipPosition), global::Ah.Teleoperation.FingerTipPosition.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ah.Teleoperation.PinchData), global::Ah.Teleoperation.PinchData.Parser, new[]{ "PinchValue", "DistanceToThumb" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ah.Teleoperation.HandConfiguration), global::Ah.Teleoperation.HandConfiguration.Parser, new[]{ "Thumb", "Index", "Middle", "Ring", "IndexPinch", "MiddlePinch", "RingPinch" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ah.Teleoperation.HandTeleoperationCommand), global::Ah.Teleoperation.HandTeleoperationCommand.Parser, new[]{ "LeftHand", "RightHand" }, new[]{ "LeftHand", "RightHand" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CalibrationData : pb::IMessage<CalibrationData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CalibrationData> _parser = new pb::MessageParser<CalibrationData>(() => new CalibrationData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CalibrationData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ah.Teleoperation.AmazingHandReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalibrationData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalibrationData(CalibrationData other) : this() {
      thumbLength_ = other.thumbLength_;
      indexLength_ = other.indexLength_;
      middleLength_ = other.middleLength_;
      ringLength_ = other.ringLength_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalibrationData Clone() {
      return new CalibrationData(this);
    }

    /// <summary>Field number for the "thumb_length" field.</summary>
    public const int ThumbLengthFieldNumber = 1;
    private float thumbLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ThumbLength {
      get { return thumbLength_; }
      set {
        thumbLength_ = value;
      }
    }

    /// <summary>Field number for the "index_length" field.</summary>
    public const int IndexLengthFieldNumber = 2;
    private float indexLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float IndexLength {
      get { return indexLength_; }
      set {
        indexLength_ = value;
      }
    }

    /// <summary>Field number for the "middle_length" field.</summary>
    public const int MiddleLengthFieldNumber = 3;
    private float middleLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MiddleLength {
      get { return middleLength_; }
      set {
        middleLength_ = value;
      }
    }

    /// <summary>Field number for the "ring_length" field.</summary>
    public const int RingLengthFieldNumber = 4;
    private float ringLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RingLength {
      get { return ringLength_; }
      set {
        ringLength_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CalibrationData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CalibrationData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ThumbLength, other.ThumbLength)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(IndexLength, other.IndexLength)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MiddleLength, other.MiddleLength)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RingLength, other.RingLength)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ThumbLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ThumbLength);
      if (IndexLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(IndexLength);
      if (MiddleLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MiddleLength);
      if (RingLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RingLength);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ThumbLength != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(ThumbLength);
      }
      if (IndexLength != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(IndexLength);
      }
      if (MiddleLength != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MiddleLength);
      }
      if (RingLength != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(RingLength);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ThumbLength != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(ThumbLength);
      }
      if (IndexLength != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(IndexLength);
      }
      if (MiddleLength != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MiddleLength);
      }
      if (RingLength != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(RingLength);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ThumbLength != 0F) {
        size += 1 + 4;
      }
      if (IndexLength != 0F) {
        size += 1 + 4;
      }
      if (MiddleLength != 0F) {
        size += 1 + 4;
      }
      if (RingLength != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CalibrationData other) {
      if (other == null) {
        return;
      }
      if (other.ThumbLength != 0F) {
        ThumbLength = other.ThumbLength;
      }
      if (other.IndexLength != 0F) {
        IndexLength = other.IndexLength;
      }
      if (other.MiddleLength != 0F) {
        MiddleLength = other.MiddleLength;
      }
      if (other.RingLength != 0F) {
        RingLength = other.RingLength;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            ThumbLength = input.ReadFloat();
            break;
          }
          case 21: {
            IndexLength = input.ReadFloat();
            break;
          }
          case 29: {
            MiddleLength = input.ReadFloat();
            break;
          }
          case 37: {
            RingLength = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            ThumbLength = input.ReadFloat();
            break;
          }
          case 21: {
            IndexLength = input.ReadFloat();
            break;
          }
          case 29: {
            MiddleLength = input.ReadFloat();
            break;
          }
          case 37: {
            RingLength = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FingerTipPosition : pb::IMessage<FingerTipPosition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FingerTipPosition> _parser = new pb::MessageParser<FingerTipPosition>(() => new FingerTipPosition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FingerTipPosition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ah.Teleoperation.AmazingHandReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FingerTipPosition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FingerTipPosition(FingerTipPosition other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FingerTipPosition Clone() {
      return new FingerTipPosition(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FingerTipPosition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FingerTipPosition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FingerTipPosition other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PinchData : pb::IMessage<PinchData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PinchData> _parser = new pb::MessageParser<PinchData>(() => new PinchData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PinchData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ah.Teleoperation.AmazingHandReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PinchData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PinchData(PinchData other) : this() {
      pinchValue_ = other.pinchValue_;
      distanceToThumb_ = other.distanceToThumb_ != null ? other.distanceToThumb_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PinchData Clone() {
      return new PinchData(this);
    }

    /// <summary>Field number for the "pinch_value" field.</summary>
    public const int PinchValueFieldNumber = 1;
    private float pinchValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PinchValue {
      get { return pinchValue_; }
      set {
        pinchValue_ = value;
      }
    }

    /// <summary>Field number for the "distance_to_thumb" field.</summary>
    public const int DistanceToThumbFieldNumber = 2;
    private global::Ah.Teleoperation.FingerTipPosition distanceToThumb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.FingerTipPosition DistanceToThumb {
      get { return distanceToThumb_; }
      set {
        distanceToThumb_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PinchData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PinchData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PinchValue, other.PinchValue)) return false;
      if (!object.Equals(DistanceToThumb, other.DistanceToThumb)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PinchValue != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PinchValue);
      if (distanceToThumb_ != null) hash ^= DistanceToThumb.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PinchValue != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(PinchValue);
      }
      if (distanceToThumb_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DistanceToThumb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PinchValue != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(PinchValue);
      }
      if (distanceToThumb_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DistanceToThumb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PinchValue != 0F) {
        size += 1 + 4;
      }
      if (distanceToThumb_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DistanceToThumb);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PinchData other) {
      if (other == null) {
        return;
      }
      if (other.PinchValue != 0F) {
        PinchValue = other.PinchValue;
      }
      if (other.distanceToThumb_ != null) {
        if (distanceToThumb_ == null) {
          DistanceToThumb = new global::Ah.Teleoperation.FingerTipPosition();
        }
        DistanceToThumb.MergeFrom(other.DistanceToThumb);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            PinchValue = input.ReadFloat();
            break;
          }
          case 18: {
            if (distanceToThumb_ == null) {
              DistanceToThumb = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(DistanceToThumb);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            PinchValue = input.ReadFloat();
            break;
          }
          case 18: {
            if (distanceToThumb_ == null) {
              DistanceToThumb = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(DistanceToThumb);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HandConfiguration : pb::IMessage<HandConfiguration>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandConfiguration> _parser = new pb::MessageParser<HandConfiguration>(() => new HandConfiguration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandConfiguration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ah.Teleoperation.AmazingHandReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandConfiguration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandConfiguration(HandConfiguration other) : this() {
      thumb_ = other.thumb_ != null ? other.thumb_.Clone() : null;
      index_ = other.index_ != null ? other.index_.Clone() : null;
      middle_ = other.middle_ != null ? other.middle_.Clone() : null;
      ring_ = other.ring_ != null ? other.ring_.Clone() : null;
      indexPinch_ = other.indexPinch_ != null ? other.indexPinch_.Clone() : null;
      middlePinch_ = other.middlePinch_ != null ? other.middlePinch_.Clone() : null;
      ringPinch_ = other.ringPinch_ != null ? other.ringPinch_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandConfiguration Clone() {
      return new HandConfiguration(this);
    }

    /// <summary>Field number for the "thumb" field.</summary>
    public const int ThumbFieldNumber = 1;
    private global::Ah.Teleoperation.FingerTipPosition thumb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.FingerTipPosition Thumb {
      get { return thumb_; }
      set {
        thumb_ = value;
      }
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 2;
    private global::Ah.Teleoperation.FingerTipPosition index_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.FingerTipPosition Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    /// <summary>Field number for the "middle" field.</summary>
    public const int MiddleFieldNumber = 3;
    private global::Ah.Teleoperation.FingerTipPosition middle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.FingerTipPosition Middle {
      get { return middle_; }
      set {
        middle_ = value;
      }
    }

    /// <summary>Field number for the "ring" field.</summary>
    public const int RingFieldNumber = 4;
    private global::Ah.Teleoperation.FingerTipPosition ring_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.FingerTipPosition Ring {
      get { return ring_; }
      set {
        ring_ = value;
      }
    }

    /// <summary>Field number for the "index_pinch" field.</summary>
    public const int IndexPinchFieldNumber = 6;
    private global::Ah.Teleoperation.PinchData indexPinch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.PinchData IndexPinch {
      get { return indexPinch_; }
      set {
        indexPinch_ = value;
      }
    }

    /// <summary>Field number for the "middle_pinch" field.</summary>
    public const int MiddlePinchFieldNumber = 7;
    private global::Ah.Teleoperation.PinchData middlePinch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.PinchData MiddlePinch {
      get { return middlePinch_; }
      set {
        middlePinch_ = value;
      }
    }

    /// <summary>Field number for the "ring_pinch" field.</summary>
    public const int RingPinchFieldNumber = 8;
    private global::Ah.Teleoperation.PinchData ringPinch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.PinchData RingPinch {
      get { return ringPinch_; }
      set {
        ringPinch_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandConfiguration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandConfiguration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Thumb, other.Thumb)) return false;
      if (!object.Equals(Index, other.Index)) return false;
      if (!object.Equals(Middle, other.Middle)) return false;
      if (!object.Equals(Ring, other.Ring)) return false;
      if (!object.Equals(IndexPinch, other.IndexPinch)) return false;
      if (!object.Equals(MiddlePinch, other.MiddlePinch)) return false;
      if (!object.Equals(RingPinch, other.RingPinch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (thumb_ != null) hash ^= Thumb.GetHashCode();
      if (index_ != null) hash ^= Index.GetHashCode();
      if (middle_ != null) hash ^= Middle.GetHashCode();
      if (ring_ != null) hash ^= Ring.GetHashCode();
      if (indexPinch_ != null) hash ^= IndexPinch.GetHashCode();
      if (middlePinch_ != null) hash ^= MiddlePinch.GetHashCode();
      if (ringPinch_ != null) hash ^= RingPinch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (thumb_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Thumb);
      }
      if (index_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Index);
      }
      if (middle_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Middle);
      }
      if (ring_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Ring);
      }
      if (indexPinch_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(IndexPinch);
      }
      if (middlePinch_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(MiddlePinch);
      }
      if (ringPinch_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(RingPinch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (thumb_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Thumb);
      }
      if (index_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Index);
      }
      if (middle_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Middle);
      }
      if (ring_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Ring);
      }
      if (indexPinch_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(IndexPinch);
      }
      if (middlePinch_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(MiddlePinch);
      }
      if (ringPinch_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(RingPinch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (thumb_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Thumb);
      }
      if (index_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Index);
      }
      if (middle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Middle);
      }
      if (ring_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ring);
      }
      if (indexPinch_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IndexPinch);
      }
      if (middlePinch_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MiddlePinch);
      }
      if (ringPinch_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RingPinch);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandConfiguration other) {
      if (other == null) {
        return;
      }
      if (other.thumb_ != null) {
        if (thumb_ == null) {
          Thumb = new global::Ah.Teleoperation.FingerTipPosition();
        }
        Thumb.MergeFrom(other.Thumb);
      }
      if (other.index_ != null) {
        if (index_ == null) {
          Index = new global::Ah.Teleoperation.FingerTipPosition();
        }
        Index.MergeFrom(other.Index);
      }
      if (other.middle_ != null) {
        if (middle_ == null) {
          Middle = new global::Ah.Teleoperation.FingerTipPosition();
        }
        Middle.MergeFrom(other.Middle);
      }
      if (other.ring_ != null) {
        if (ring_ == null) {
          Ring = new global::Ah.Teleoperation.FingerTipPosition();
        }
        Ring.MergeFrom(other.Ring);
      }
      if (other.indexPinch_ != null) {
        if (indexPinch_ == null) {
          IndexPinch = new global::Ah.Teleoperation.PinchData();
        }
        IndexPinch.MergeFrom(other.IndexPinch);
      }
      if (other.middlePinch_ != null) {
        if (middlePinch_ == null) {
          MiddlePinch = new global::Ah.Teleoperation.PinchData();
        }
        MiddlePinch.MergeFrom(other.MiddlePinch);
      }
      if (other.ringPinch_ != null) {
        if (ringPinch_ == null) {
          RingPinch = new global::Ah.Teleoperation.PinchData();
        }
        RingPinch.MergeFrom(other.RingPinch);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (thumb_ == null) {
              Thumb = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(Thumb);
            break;
          }
          case 18: {
            if (index_ == null) {
              Index = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(Index);
            break;
          }
          case 26: {
            if (middle_ == null) {
              Middle = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(Middle);
            break;
          }
          case 34: {
            if (ring_ == null) {
              Ring = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(Ring);
            break;
          }
          case 50: {
            if (indexPinch_ == null) {
              IndexPinch = new global::Ah.Teleoperation.PinchData();
            }
            input.ReadMessage(IndexPinch);
            break;
          }
          case 58: {
            if (middlePinch_ == null) {
              MiddlePinch = new global::Ah.Teleoperation.PinchData();
            }
            input.ReadMessage(MiddlePinch);
            break;
          }
          case 66: {
            if (ringPinch_ == null) {
              RingPinch = new global::Ah.Teleoperation.PinchData();
            }
            input.ReadMessage(RingPinch);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (thumb_ == null) {
              Thumb = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(Thumb);
            break;
          }
          case 18: {
            if (index_ == null) {
              Index = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(Index);
            break;
          }
          case 26: {
            if (middle_ == null) {
              Middle = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(Middle);
            break;
          }
          case 34: {
            if (ring_ == null) {
              Ring = new global::Ah.Teleoperation.FingerTipPosition();
            }
            input.ReadMessage(Ring);
            break;
          }
          case 50: {
            if (indexPinch_ == null) {
              IndexPinch = new global::Ah.Teleoperation.PinchData();
            }
            input.ReadMessage(IndexPinch);
            break;
          }
          case 58: {
            if (middlePinch_ == null) {
              MiddlePinch = new global::Ah.Teleoperation.PinchData();
            }
            input.ReadMessage(MiddlePinch);
            break;
          }
          case 66: {
            if (ringPinch_ == null) {
              RingPinch = new global::Ah.Teleoperation.PinchData();
            }
            input.ReadMessage(RingPinch);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HandTeleoperationCommand : pb::IMessage<HandTeleoperationCommand>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandTeleoperationCommand> _parser = new pb::MessageParser<HandTeleoperationCommand>(() => new HandTeleoperationCommand());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandTeleoperationCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ah.Teleoperation.AmazingHandReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandTeleoperationCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandTeleoperationCommand(HandTeleoperationCommand other) : this() {
      leftHand_ = other.leftHand_ != null ? other.leftHand_.Clone() : null;
      rightHand_ = other.rightHand_ != null ? other.rightHand_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandTeleoperationCommand Clone() {
      return new HandTeleoperationCommand(this);
    }

    /// <summary>Field number for the "left_hand" field.</summary>
    public const int LeftHandFieldNumber = 1;
    private global::Ah.Teleoperation.HandConfiguration leftHand_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.HandConfiguration LeftHand {
      get { return leftHand_; }
      set {
        leftHand_ = value;
      }
    }

    /// <summary>Field number for the "right_hand" field.</summary>
    public const int RightHandFieldNumber = 2;
    private global::Ah.Teleoperation.HandConfiguration rightHand_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ah.Teleoperation.HandConfiguration RightHand {
      get { return rightHand_; }
      set {
        rightHand_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandTeleoperationCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandTeleoperationCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LeftHand, other.LeftHand)) return false;
      if (!object.Equals(RightHand, other.RightHand)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (leftHand_ != null) hash ^= LeftHand.GetHashCode();
      if (rightHand_ != null) hash ^= RightHand.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (leftHand_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LeftHand);
      }
      if (rightHand_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RightHand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (leftHand_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LeftHand);
      }
      if (rightHand_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RightHand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (leftHand_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeftHand);
      }
      if (rightHand_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RightHand);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandTeleoperationCommand other) {
      if (other == null) {
        return;
      }
      if (other.leftHand_ != null) {
        if (leftHand_ == null) {
          LeftHand = new global::Ah.Teleoperation.HandConfiguration();
        }
        LeftHand.MergeFrom(other.LeftHand);
      }
      if (other.rightHand_ != null) {
        if (rightHand_ == null) {
          RightHand = new global::Ah.Teleoperation.HandConfiguration();
        }
        RightHand.MergeFrom(other.RightHand);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (leftHand_ == null) {
              LeftHand = new global::Ah.Teleoperation.HandConfiguration();
            }
            input.ReadMessage(LeftHand);
            break;
          }
          case 18: {
            if (rightHand_ == null) {
              RightHand = new global::Ah.Teleoperation.HandConfiguration();
            }
            input.ReadMessage(RightHand);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (leftHand_ == null) {
              LeftHand = new global::Ah.Teleoperation.HandConfiguration();
            }
            input.ReadMessage(LeftHand);
            break;
          }
          case 18: {
            if (rightHand_ == null) {
              RightHand = new global::Ah.Teleoperation.HandConfiguration();
            }
            input.ReadMessage(RightHand);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
